NAME = Net-Telnet
VERSION = 3.04
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JROGERS

DESCRIPTION = Interact with TELNET port or other TCP ports
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the unknown license

PACKAGES += CSWpm-net-telnet
CATALOGNAME_CSWpm-net-telnet = pm_net_telnet
SPKG_DESC_CSWpm-net-telnet = Interact with TELNET port or other TCP ports
ARCHALL_CSWpm-net-telnet = 1
OBSOLETED_BY_CSWpm-net-telnet += CSWpmnettelnet
CATALOGNAME_CSWpmnettelnet = pm_nettelnet_stub

include gar/category.mk
