NAME = Apache-AuthPAM
VERSION = 0.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = HDANIEL

DESCRIPTION = authenticate apache request using PAM services
define BLURB
  This perl module is designed to work with mod_perl and the Authen::PAM
  module.
endef

DISTFILES += CSWpmapauthpam.gspec CSWpmapauthpam.depend

DEPENDS += cpan/Authen-PAM

include gar/category.mk
