GARNAME = IO-stringy
GARVERSION = 2.109
CATEGORIES = cpan
AUTHOR = ERYQ

DESCRIPTION = I/O on in-core objects like strings and arrays
define BLURB
  This toolkit primarily provides modules for performing both traditional and
  object-oriented i/o) on things other than normal filehandles; in particular,
  IO::Scalar, IO::ScalarArray, and IO::Lines.
endef

DISTFILES = $(call admfiles,CSWpmiostringy,)

include ../category.mk
