# $Id$
#
NAME = ppl
VERSION = 0.11.2
GARTYPE = v2
CATEGORIES = lib

DESCRIPTION = Parma Polyhedra Library
define BLURB
endef

MASTER_SITES = http://www.cs.unipr.it/ppl/Download/ftp/releases/$(VERSION)/
DISTFILES  = $(DISTNAME).tar.gz

VENDOR_URL = http://www.cs.unipr.it/ppl/

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk

