GARNAME = Module-Signature
GARVERSION = 0.44
CATEGORIES = cpan
AUTHOR = AUTRIJUS
GARCH = all

DESCRIPTION = module signature file manipulation
define BLURB
  Module::Signature adds cryptographic authentications to CPAN distributions,
  via the special SIGNATURE file.
endef

DISTFILES += CSWpmmodulesignature.gspec CSWpmmodulesignature.depend

DEPENDS += cpan/Text-Diff cpan/Crypt-OpenPGP cpan/PAR-Dist

include ../category.mk
