NAME = Probe-Perl
VERSION = 0.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = KWILLIAMS

DESCRIPTION = Information about the currently running perl
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmprobeperl
CATALOGNAME = pm_probeperl

ARCHALL = 1

include gar/category.mk
