GARNAME = Probe-Perl
GARVERSION = 0.01
CATEGORIES = cpan
AUTHOR = KWILLIAMS

DESCRIPTION = Information about the currently running perl
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmprobeperl
CATALOGNAME = pm_probeperl

ARCHALL = 1

include gar/category.mk
