NAME = PerlIO-via-Bzip2
VERSION = 0.02
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ARJEN

DESCRIPTION = PerlIO layer for Bzip2 (de)compression
define BLURB
endef

PACKAGES = CSWpmperlioviabzip2
CATALOGNAME = pm_perlioviabzip2

Warning: prerequisite Compress::Bzip2 1.03 not found.


include gar/category.mk
