NAME = Mail-Box-Parser-C
VERSION = 3.006
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MARKOV

DESCRIPTION = parsing folders for MailBox with C routines
define BLURB
  This is an optional module for MailBox, and will (once installed)
  automatically be used by MailBox to parse e-mail message content when the
  message is supplied as file-handle. In all other cases, MailBox will use
  Mail::Box::Parser::Perl.
endef

DEPENDS += cpan/Mail-Box

DISTFILES += CSWpmmailboxpc.gspec

include gar/category.mk
