GARNAME = CGP-CLI
GARVERSION = 2.7.5
CATEGORIES = cpan
AUTHOR = JBUHACOFF

DESCRIPTION = CommunigatePro Command Line Interface perl module
define BLURB
  This is Stalker's CLI.pm packaged for CPAN. The original CLI.pm file is available from Stalker's website at:
    http://www.stalker.com/CGPerl/CLI.pm
  The only changes are the addition of the VERSION variable for MakeMaker and this short POD at the end.
endef

DISTFILES += $(call admfiles,CSWpmcgpcli)

include gar/category.mk
