NAME = cronedit
VERSION = 0.3.0
CATEGORIES = rbgems

DESCRIPTION = A Ruby editor library for the crontab

define BLURB
endef

DISTFILES += COPYING

LICENSE = COPYING

ARCHALL = 1

include gar/category.mk
