NAME = Net-LibIDN
VERSION = 0.12
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = THOR

DESCRIPTION = Perl bindings for GNU Libidn
define BLURB
  Perl bindings for GNU LibIDN
endef

CATALOG_RELEASE = unstable

LICENSE = Artistic

PACKAGES += CSWpm-net-libidn
CATALOGNAME_CSWpm-net-libidn = pm_net_libidn
SPKG_DESC_CSWpm-net-libidn = Perl bindings for GNU Libidn
RUNTIME_DEP_PKGS_CSWpm-net-libidn += CSWlibidn11

include gar/category.mk
