NAME = hpricot
VERSION = 0.8.4
CATEGORIES = rbgems

DESCRIPTION = A swift, liberal HTML parser with a fantastic library

define BLURB
  A swift, liberal HTML parser with a fantastic library
endef

LICENSE = COPYING

RUNTIME_DEP_PKGS_CSWrb18-hpricot-0-8-4 += CSWlibruby18-1

include gar/category.mk
