NAME = JSON
VERSION = 2.50
CATEGORIES = cpan
AUTHOR = MAKAMAKA

DESCRIPTION = JSON (JavaScript Object Notation) encoder/decoder
define BLURB
  JSON (JavaScript Object Notation) encoder/decoder
endef

DISTFILES += COPYING

PACKAGES = CSWpm-json
CATALOGNAME = pm_json
SPKG_DESC_CSWpm-json = $(DESCRIPTION)
ARCHALL = 1
OBSOLETES_CSWpm-json = CSWpmjson
CATALOGNAME_CSWpmjson = pm_json_stub

include gar/category.mk
