NAME = hoe
VERSION = 2.6.1
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = A rake/rubygems helper for project Rakefiles
define BLURB
  Hoe is a rake/rubygems helper for project Rakefiles. It helps you manage and maintain, and release your project and includes a dynamic plug-in system allowing for easy extensibility. Hoe ships with plug-ins for all your usual project tasks including rdoc generation, testing, packaging, and deployment. See class rdoc for help. Hint: `ri Hoe` or any of the plugins listed below. For extra goodness, see: http://seattlerb.rubyforge.org/hoe/Hoe.pdf
endef

DISTFILES = COPYING

PACKAGES = CSWgem-hoe
CATALOGNAME = gem_hoe

LICENSE = COPYING

ARCHALL = 1

include gar/category.mk
