NAME = Text-Diff
VERSION = 1.41
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = OVID

DESCRIPTION = Perform diffs on files and record sets
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-text-diff
CATALOGNAME_CSWpm-text-diff = pm_text_diff
SPKG_DESC_CSWpm-text-diff = Perform diffs on files and record sets
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-text-diff = 1
RUNTIME_DEP_PKGS_CSWpm-text-diff += CSWpm-algorithm-diff
OBSOLETED_BY_CSWpm-text-diff += CSWpmtextdiff
CATALOGNAME_CSWpmtextdiff = pm_textdiff_stub

include gar/category.mk
