GARNAME = sol-inst
GARVERSION = 0.90a
CATEGORIES = cpan
AUTHOR = CHRISJ

DESCRIPTION = access basic Solaris installation information
define BLURB
  sol-inst is a collection of Perl modules to access basic installation
  information on a Solaris system.
endef

WORKSRC = $(WORKDIR)/Solaris

DISTFILES += CSWpmsolinst.gspec

include ../category.mk
