NAME = Memoize-Memcached
VERSION = 0.03
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DTRISCHUK

DESCRIPTION = Use a memcached cache to memoize functions
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the unknown license

PACKAGES += CSWpm-memoize-memcached
CATALOGNAME_CSWpm-memoize-memcached = pm_memoize_memcached
SPKG_DESC_CSWpm-memoize-memcached = Use a memcached cache to memoize functions
ARCHALL_CSWpm-memoize-memcached = 1
RUNTIME_DEP_PKGS_CSWpm-memoize-memcached += CSWpm-cache-memcached

include gar/category.mk
