NAME = Text-Glob
VERSION = 0.08
CATEGORIES = cpan
AUTHOR = RCLAMP

DESCRIPTION = Match globbing patterns against text
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmtextglob
CATALOGNAME = pm_textglob

ARCHALL = 1

include gar/category.mk
