GARNAME = BerkeleyDB
GARVERSION = 0.41
CATEGORIES = cpan
AUTHOR = PMQS

DESCRIPTION = BerkeleyDB module
define BLURB
  Includes BerkeleyDB, BerkeleyDB::Btree, BerkeleyDB::Hash
endef

PACKAGES = CSWpmberkeleydb
CATALOGNAME = pm_berkeleydb

PATCHFILES = CSWpmberkeleydb.config.in.diff

NOISALIST = 1
EXTRA_LIB = /opt/csw/bdb48/lib

REQUIRED_PKGS = CSWbdb48

include gar/category.mk
