# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = python-keyczar
VERSION = 0.715
CATEGORIES = python

DESCRIPTION = Toolkit for safe and simple cryptography

MASTER_SITES = $(PYPI_MIRROR)
DISTFILES += $(DISTNAME).tar.gz

PACKAGES += CSWpy-keyczar
SPKG_DESC_CSWpy-keyczar = Toolkit for safe and simple cryptography
# PKGFILES is catchall
ARCHALL_CSWpy-keyczar = 1

include gar/category.mk
