NAME = Net-SSH
VERSION = 0.09
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = IVAN

DESCRIPTION = Perl extension for secure shell
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmnetssh
CATALOGNAME = pm_netssh

ARCHALL = 1

include gar/category.mk
