NAME = Unicode-LineBreak
VERSION = 2013.11
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = NEZUMI

DESCRIPTION = UAX #14 Unicode Line Breaking Algorithm
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = ARTISTIC

PACKAGES += CSWpm-unicode-linebreak
SPKG_DESC_CSWpm-unicode-linebreak = UAX #14 Unicode Line Breaking Algorithm
RUNTIME_DEP_PKGS_CSWpm-unicode-linebreak += CSWpm-mime-charset
RUNTIME_DEP_PKGS_CSWpm-unicode-linebreak += CSWlibthai0

include gar/category.mk
