GARNAME = Data-Flow
GARVERSION = 0.08
CATEGORIES = cpan
AUTHOR = RADOS

DESCRIPTION = simple-minded recipe-controlled build of data
define BLURB
  Perl extension for simple-minded recipe-controlled build of data.
endef

DISTFILES += CSWpmdataflow.gspec

include ../category.mk
