# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = waitress
VERSION = 0.8.9
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Waitress WSGI server

TEST_SCRIPTS =
DISTFILES  = $(DISTNAME).tar.gz
ARCHALL_CSWpy-$(NAME) = 1

include gar/category.mk

