NAME = Text-CharWidth
VERSION = 0.04
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = KUBOTA

DESCRIPTION = 
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the  license

PACKAGES += CSWpm-text-charwidth
CATALOGNAME_CSWpm-text-charwidth = pm_text_charwidth
SPKG_DESC_CSWpm-text-charwidth = Provides equivalent feature as wcwidth(3) and wcswidth(3)

include gar/category.mk
