NAME = Barcode-Code128
VERSION = 2.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = WRW

DESCRIPTION = Generate CODE 128 bar codes
define BLURB
  Generate CODE 128 bar codes
endef

DISTFILES += COPYING

PACKAGES = CSWpmbarcodecode128
CATALOGNAME = pm_barcodecode128
ARCHALL = 1

BUILD_DEP_PKGS = CSWpmgd

SKIPTEST = 1

include gar/category.mk
