NAME = common-sense
VERSION = 3.4
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MLEHMANN

DESCRIPTION = Some sane defaults for Perl programs
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-common-sense
CATALOGNAME_CSWpm-common-sense = pm_common_sense
SPKG_DESC_CSWpm-common-sense = Some sane defaults for Perl programs
ARCHALL_CSWpm-common-sense = 1
OBSOLETED_BY_CSWpm-common-sense += CSWpmcommonsense
CATALOGNAME_CSWpmcommonsense = pm_commonsense_stub

include gar/category.mk
