GARNAME = Test-Warn
GARVERSION = 0.21
CATEGORIES = cpan
AUTHOR = CHORNY

DESCRIPTION = Extension to test methods for warnings
define BLURB
    Extension to test methods for warnings
endef

MODDIST = $(GARNAME)-$(GARVERSION).zip

DISTFILES += COPYING

PACKAGES = CSWpmtestwarn
CATALOGNAME = pm_testwarn
ARCHALL = 1

RUNTIME_DEP_PKGS += CSWpmtreedagnode CSWpmsubuplevel 

include gar/category.mk
