GARNAME = Solaris-Sysconf
GARVERSION = 0.01
CATEGORIES = cpan
AUTHOR = AGOLOMSH

DESCRIPTION = get configurable system variables
define BLURB
  The Solaris::Sysconf module is a simple interface to sysconf(3C) library
  function, which provides a method for an  application to  determine  the
  current  value  of a configurable system limit or option (variable). The
  argument to the sysconf method represents the system variable to be queried.
  The symbolic constants that represent the names of the variables, accessible
  through sysconf are defined in <limits.h> and <unistd.h>. All these
  constants are exported by default by the Solaris::Sysconf module.
endef

DISTFILES += CSWpmsolarissysconf.gspec

include ../category.mk
