#!/bin/sh

# preremove with SMF support for MailScanner
# 2008-09-04 Peter Bonivart

CHROOT=/usr/sbin/chroot
ECHO=/usr/bin/echo
RM=/usr/bin/rm
RMDIR=/usr/bin/rmdir
SVCADM=/usr/sbin/svcadm
SVCCFG=/usr/sbin/svccfg

CONFFILES=$BASEDIR/share/doc/mailscanner/conffiles
ETC=$BASEDIR/mailscanner/etc
MSDIR=$PKG_INSTALL_ROOT/var/spool/MailScanner
SADIR=$PKG_INSTALL_ROOT/etc/opt/csw/spamassassin

# If removing from a filesystem that is not running the OS, exit this script.
if [ ! x"$PKG_INSTALL_ROOT" = x"" ]; then
  exit 0
fi

# check csw.conf
if [ -f $PKG_INSTALL_ROOT/opt/csw/etc/csw.conf ] ; then
  . $PKG_INSTALL_ROOT/opt/csw/etc/csw.conf
fi
if [ -f $PKG_INSTALL_ROOT/etc/opt/csw/csw.conf ] ; then
  . $PKG_INSTALL_ROOT/etc/opt/csw/csw.conf
fi

# SMF
smf=no
if [ -f $PKG_INSTALL_ROOT/usr/sbin/svccfg -a -f $PKG_INSTALL_ROOT/usr/sbin/svcadm ]; then
  if [ "$use_smf" != "no" ]; then
    smf=yes
  fi
fi

# killing mailscanner
$ECHO "Stopping MailScanner."
if [ "$smf" = "yes" ]; then
  $SVCADM disable -s svc:network/smtp/cswmailscanner > /dev/null 2>&1
  $SVCADM disable -s svc:network/smtp/cswmailscannersendmail > /dev/null 2>&1
else
  /etc/init.d/cswmailscanner stop >/dev/null 2>&1
  /etc/init.d/cswmailscanner.sendmail stop >/dev/null 2>&1
fi

if [ "$smf" = "yes" ]; then
  # Unregister with SMF
  $ECHO "Unregister with SMF."
  $SVCCFG delete svc:network/smtp/cswmailscanner > /dev/null 2>&1
  $SVCCFG delete svc:network/smtp/cswmailscannersendmail > /dev/null 2>&1
fi

# remove mailscanner dir
$ECHO "Removing $MSDIR directory."
if [ -d "$MSDIR" ]; then
  dirs=`find $MSDIR -type d | wc -l | awk '{print $1}'` 
  test -f "$MSDIR/incoming/SpamAssassin.cache.db"
  sacache=$?
  if [ "$dirs" -le "3" -a "$sacache" -ne "0" ]; then
    $RM -rf $MSDIR
  else
    $ECHO "! $MSDIR does not seem empty. Not removing."
  fi
else
  $ECHO "! No directory found."
fi

# remove symlink to spam.assassin.prefs.conf
if [ -h "$SADIR/mailscanner.cf" ]; then
  $ECHO "Removing symlink to spam.assassin.prefs.conf."
  $RM $SADIR/mailscanner.cf
fi

# remove symlink cswmailscanner
$ECHO "Removing symlink cswmailscanner."
$RM -f $BASEDIR/bin/cswmailscanner

# remove x conf file if same as x.CSW
$ECHO "Removing configuration files that have not been modified."
for i in `cat $CONFFILES`
do
  cmp -s "$ETC/$i" "$ETC/${i}.CSW"
  if [ "x$?" = "x1" ]; then
    $ECHO
    echo "! $i modified, will not remove it."
  else
    $ECHO ".\c"
    $RM -f $ETC/$i
  fi
done
$ECHO

exit 0
