GARNAME = XML-XPath
GARVERSION = 1.13
CATEGORIES = cpan
AUTHOR = MSERGEANT

DESCRIPTION = a set of modules for parsing and evaluating XPath statements
define BLURB
  This module aims to comply exactly to the XPath specification at
  http://www.w3.org/TR/xpath and yet allow extensions to be added in the form
  of functions. Modules such as XSLT and XPointer may need to do this as they
  support functionality beyond XPath.
endef

DISTFILES += CSWpmxmlxpath.gspec CSWpmxmlxpath.depend

DEPENDS += cpan/XML-Parser

include gar/category.mk
