NAME = BSD-Resource
VERSION = 1.28
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JHI

DESCRIPTION = BSD process resource limit and priority functions
define BLURB
  BSD process resource limit and priority functions
endef

DISTFILES += CSWpmbsdresource.gspec

include gar/category.mk
