NAME = File-Find-Rule
VERSION = 0.33
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RCLAMP

DESCRIPTION = Alternative interface to File::Find
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the unknown license

PACKAGES += CSWpm-file-find-rule
CATALOGNAME_CSWpm-file-find-rule = pm_file_find_rule
SPKG_DESC_CSWpm-file-find-rule = Alternative interface to File::Find
ARCHALL_CSWpm-file-find-rule = 1
RUNTIME_DEP_PKGS_CSWpm-file-find-rule += CSWpm-number-compare
RUNTIME_DEP_PKGS_CSWpm-file-find-rule += CSWpm-text-glob
OBSOLETED_BY_CSWpm-file-find-rule += CSWpmfilefindrule
CATALOGNAME_CSWpmfilefindrule = pm_filefindrule_stub

include gar/category.mk
