NAME = Text-Quoted
VERSION = 2.06
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RUZ

DESCRIPTION = extract the structure of a quoted mail message
define BLURB
  Text::Quoted examines the structure of some text which may contain multiple
  different levels of quoting, and turns the text into a nested data
  structure.
endef

RUNTIME_DEP_PKGS = CSWpmtxtautofmt
BUILD_DEP_PKGS = CSWpmtxtautofmt

CATALOGNAME = pm_txtquoted
PACKAGES    = CSWpmtxtquoted

ARCHALL_CSWpmtxtquoted = 1

LICENSE = README

include gar/category.mk

