NAME = ruby-ip
VERSION = 0.9.0
CATEGORIES = rbgems

DESCRIPTION = IP address manipulation library

define BLURB
  IP adres manipulation library
endef

LICENSE = LICENSE.txt

ARCHALL = 1

include gar/category.mk
