NAME = XML-TreePP
VERSION = 0.41
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = KAWASAKI

DESCRIPTION = 
define BLURB
  XML::TreePP module parses an XML document and expands it for a hash tree.
  This generates an XML document from a hash tree as the opposite way around.
  This is a pure Perl implementation and requires no modules depended. This can
  also fetch and parse an XML document from remote web server like the
  XMLHttpRequest object does at JavaScript language.
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-xml-treepp
CATALOGNAME_CSWpm-xml-treepp = pm_xml_treepp
SPKG_DESC_CSWpm-xml-treepp = 
ARCHALL_CSWpm-xml-treepp = 1
RUNTIME_DEP_PKGS_CSWpm-xml-treepp += CSWpm-libwww-perl

include gar/category.mk
