# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = vobject
VERSION = 0.8.1c
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Python library for parsing and generating vCard and vCalendar files
define BLURB
  Long description
endef

MASTER_SITES = http://vobject.skyhouseconsulting.com/
DISTFILES  = $(DISTNAME).tar.gz

# EXTRA_MERGE_EXCLUDE_FILES +=  .*/.*\.py[co]
PACKAGES = CSWpy-vobject
ARCHALL_CSWpy-vobject = 1

include gar/category.mk

