NAME = Calendar-CSA
VERSION = 0.8
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = KJALB

DESCRIPTION = Perl extension to interface with CDE Calendar Manager
define BLURB
  Perl extension to interface with CDE Calendar Manager.
endef

PACKAGES = CSWpmccsa
CATALOGNAME = pm_calendar_csa

include gar/category.mk
