NAME = Email-MIME-Encodings
VERSION = 1.313
GARTYPE = v2
CATEGORIES = cpan
AUTHOR = RJBS

DESCRIPTION = A unified interface to MIME encoding and decoding
define BLURB
  A unified interface to MIME encoding and decoding
endef

PACKAGES = CSWpm-email-mime-encodings
CATALOGNAME = pm_email_mime_encodings

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk

