GARNAME = Terminal
GARVERSION = 0.2.6
CATEGORIES = xfce

DESCRIPTION = Xfce Terminal Emulator
define BLURB
   Xfce Terminal Emulator
endef

DISTFILES  = $(GARNAME)-$(GARVERSION).tar.bz2
DISTFILES += $(call admfiles,CSWxfceterminal, depend)

include ../category.mk

