# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = python-magic
VERSION = 0.3.1
PACKAGES = CSWpy-magic
CATALOGNAME_CSWpy-magic = py_magic
CATEGORIES = python
DESCRIPTION = A python wrapper for libmagic, can classify files according to magic number tests
define BLURB
endef
SPKG_SOURCEURL = http://github.com/ahupp/python-magic
MASTER_SITES = http://pypi.python.org/packages/source/p/python-magic/
DISTFILES  = $(NAME)-$(VERSION).tar.gz
UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz
LICENSE = README
ARCHALL_CSWpy-magic = 1
include gar/category.mk
