NAME = Date-ICal
VERSION = 1.72
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RBOW

DESCRIPTION = Perl extension for ICalendar date objects
define BLURB
endef

PACKAGES = CSWpmdateical
CATALOGNAME = pm_dateical

DEP_PKGS = CSWpmdateleapyear

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
