NAME = Error
VERSION = 0.17016
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = SHLOMIF

DESCRIPTION = Error/exception handling in an OO-ish way
define BLURB
  The Error package provides two interfaces. Firstly Error provides a
  procedural interface to exception handling. Secondly Error is a base class
  for errors/exceptions that can either be thrown, for subsequent catch, or
  can simply be recorded.
endef

DISTFILES = COPYING

PACKAGES = CSWpmerror
CATALOGNAME = pm_error

BUILD_DEP_PKGS = CSWpmtestpodcoverage

ARCHALL = 1

include gar/category.mk
