# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = guppy
VERSION = 0.1.9
CATEGORIES = python
GARTYPE = v2
DESCRIPTION  = Programming environment providing object and heap memory sizing,
DESCRIPTION += profiling and analysis
define BLURB
endef
SPKG_SOURCEURL = http://guppy-pe.sourceforge.net/
MASTER_SITES = http://pypi.python.org/packages/source/g/guppy/
DISTFILES  = $(NAME)-$(VERSION).tar.gz
UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz
PACKAGES = CSWpy-guppy
CATALOGNAME_CSWpy-guppy = py_guppy
TEST_SCRIPTS =
CONFIGURE_ARGS = $(DIRPATHS)
LICENSE = PKG-INFO
include gar/category.mk
