NAME = shoulda
VERSION = 2.11.3
CATEGORIES = rbgems

DESCRIPTION = Making tests easy on the fingers and eyes

define BLURB
  Making tests easy on the fingers and eyes
endef

ARCHALL = 1

include gar/category.mk
