NAME = Net-Netmask
VERSION = 1.9016
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MUIR

DESCRIPTION = Parse, manipulate and lookup IP network blocks
define BLURB
endef

DISTFILES += COPYING

MASTER_SITES = http://search.cpan.org/CPAN/authors/id/M/MU/MUIR/modules/
DISTFILES  = $(DISTNAME).tar.gz

PACKAGES = CSWpm-net-netmask
CATALOGNAME = pm_net_netmask
SPKG_DESC_CSWpm-net-netmask = $(DESCRIPTION)
OBSOLETED_BY_CSWpm-net-netmask = CSWpmnetnetmask
CATALOGNAME_CSWpmnetnetmask = pm_netnetmask

ARCHALL = 1

include gar/category.mk
