#!/bin/sh

ARCH=`uname -p`
PKGINFO=sos11-${ARCH}-pkginfo
WORK=work/sos11-${ARCH}
(cd /opt/studio/SOS11; pkgproto .;
 echo "i pkginfo=${PKGINFO}") > sos11-${ARCH}-pkgproto
mkdir -p ${WORK}
pkgmk -a ${ARCH} \
	-b /opt/studio/SOS11 \
	-f sos11-${ARCH}-pkgproto \
	-p "$(LOGNAME)@$(hostname)-$(date '+%Y%m%d%H%M%S')" \
	-o -d ${WORK}
pkgtrans ${WORK} /dev/fd/1 CSWsos11 | pigz -c -9 > sos11-11,REV=`date '+%Y.%m.%d'`-`uname -s``uname -r`-${ARCH}-CSW.pkg.gz
