GARNAME = B-Flags
GARVERSION = 0.04
CATEGORIES = cpan
AUTHOR = RURBAN

DESCRIPTION = Friendlier flags for B
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpm-b-flags
CATALOGNAME = pm_b_flags

include gar/category.mk
