GARNAME = Algorithm-Annotate
GARVERSION = 0.10
CATEGORIES = cpan
AUTHOR = CLKAO

DESCRIPTION = represent a series of changes in annotate form
define BLURB
  Algorithm::Annotate generates a list that is useful for generating output
  simliar to cvs annotate.
endef

DISTFILES = $(call admfiles,CSWpmalgannotate,depend prototype)

DEPENDS += cpan/Algorithm-Diff

include gar/category.mk
