NAME = Algorithm-Annotate
VERSION = 0.10
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CLKAO

DESCRIPTION = Represent a series of changes in annotate form
define BLURB
  Algorithm::Annotate generates a list that is useful for generating output
  simliar to cvs annotate.
endef

RUNTIME_DEP_PKGS = CSWpmalgdiff

PACKAGES = CSWpmalgannotate
CATALOGNAME = pm_algorithmannotate

ARCHALL = 1

include gar/category.mk
