GARNAME = XML-RegExp
GARVERSION = 0.03
CATEGORIES = cpan
AUTHOR = TJMATHER
GARCH = all

DESCRIPTION = regular expressions for XML tokens
define BLURB
  This package contains regular expressions for the following XML tokens:
  BaseChar, Ideographic, Letter, Digit, Extender, CombiningChar, NameChar,
  EntityRef, CharRef, Reference, Name, NmToken, and AttValue.
endef

DISTFILES += CSWpmxmlregexp.gspec

include ../category.mk
