NAME = Archive-Zip
VERSION = 1.30
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ADAMK

DESCRIPTION = Provides an interface to ZIP archive files
define BLURB
endef

PACKAGES = CSWpm-archive-zip
CATALOGNAME = pm_archive_zip
SPKG_DESC_CSWpm-archive-zip = $(DESCRIPTION)
OBSOLETED_BY_CSWpm-archive-zip = CSWpmarchivezip
CATALOGNAME_CSWpmarchivezip = pm_archivezip

ARCHALL = 1

LICENSE = LICENSE

RUNTIME_DEP_PKGS = CSWpm-io-compress

include gar/category.mk
