GARNAME = Crypt-IDEA
GARVERSION = 1.08
CATEGORIES = cpan
AUTHOR = DPARIS

DESCRIPTION = Perl interface to IDEA block cipher
define BLURB
  This perl extension is an implementation of the IDEA block cipher algorithm.
endef

DISTFILES = $(call admfiles,CSWpmcryptidea,depend prototype)

include ../category.mk
