# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = progressbar
VERSION = 2.3
CATEGORIES = python
GARTYPE = v2

DESCRIPTION = Text progressbar library for Python

GOOGLE_PROJECT = python-progressbar
MASTER_SITES += $(GOOGLE_MIRROR)
DISTFILES += $(DISTNAME).tar.gz
UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz

VENDOR_URL = http://pypi.python.org/pypi/progressbar
LICENSE = LICENSE.txt

#TEST_SCRIPTS =

PACKAGES = CSWpy-progressbar
ARCHALL_CSWpy-progressbar = 1

include gar/category.mk
