NAME = DateTime-Format-Flexible
VERSION = 0.24
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = THINC

DESCRIPTION = Flexibly parse strings and turn them into DateTime objects
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-datetime-format-flexible
CATALOGNAME_CSWpm-datetime-format-flexible = pm_datetime_format_flexible
SPKG_DESC_CSWpm-datetime-format-flexible = Flexibly parse strings and turn them into DateTime objects
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-datetime-format-flexible = 1
RUNTIME_DEP_PKGS_CSWpm-datetime-format-flexible += CSWpm-datetime
RUNTIME_DEP_PKGS_CSWpm-datetime-format-flexible += CSWpm-test-mocktime
RUNTIME_DEP_PKGS_CSWpm-datetime-format-flexible += CSWpm-datetime-timezone
RUNTIME_DEP_PKGS_CSWpm-datetime-format-flexible += CSWpm-datetime-format-builder
RUNTIME_DEP_PKGS_CSWpm-datetime-format-flexible += CSWpm-list-moreutils

include gar/category.mk
