GARNAME = Carp-Clan
GARVERSION = 5.3
CATEGORIES = cpan
AUTHOR = STBEY

DESCRIPTION = report errors from perspective of caller of a "clan" of modules
define BLURB
  This module is based on "Carp.pm" from Perl 5.005_03. It has been modified
  to skip all package names matching the pattern given in the "use" statement
  inside the "qw()" term (or argument list).
endef

DISTFILES += $(call admfiles,CSWpmcarpclan,prototype)

include gar/category.mk
