NAME = HTML-Template-Pro
VERSION = 0.9504
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = VIY

DESCRIPTION = Perl/XS module to use HTML Templates from CGI scripts
define BLURB
  Perl/XS module to use HTML Templates from CGI scripts
endef

DISTFILES += COPYING

PACKAGES = CSWpmhtmltemplatepro
CATALOGNAME = pm_htmltemplatepro

RUNTIME_DEP_PKGS_CSWpmhtmltemplatepro += CSWpmjson CSWlibpcre0

include gar/category.mk
