NAME = Data-Hierarchy
VERSION = 0.34
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CLKAO

DESCRIPTION = Handle data in a hierarchical structure
define BLURB
  Data::Hierarchy provides a simple interface for manipulating inheritable
  data attached to a hierarchical environment (like filesystem).
endef

BUILD_DEP_PKGS = CSWpmtstexcept
RUNTIME_DEP_PKGS = CSWpmclone

PACKAGES = CSWpmdatahier
CATALOGNAME = pm_datahier

ARCHALL = 1

include gar/category.mk
