GARNAME = Data-Hierarchy
GARVERSION = 0.34
CATEGORIES = cpan
AUTHOR = CLKAO

DESCRIPTION = Handle data in a hierarchical structure
define BLURB
  Data::Hierarchy provides a simple interface for manipulating inheritable
  data attached to a hierarchical environment (like filesystem).
endef

PREREQUISITE_PKGS = CSWpmtstexcept
REQUIRED_PKGS = CSWpmclone

PACKAGES = CSWpmdatahier
CATALOGNAME = pm_datahier

ARCHALL = 1

include gar/category.mk
