GARNAME = HTTP-DAV
GARVERSION = 0.31
CATEGORIES = cpan
AUTHOR = PCOLLINS

DESCRIPTION = A WebDAV client library for Perl5
define BLURB
  HTTP::DAV is a Perl API for interacting with and modifying content on
  webservers using the WebDAV protocol. Now you can LOCK, DELETE and PUT files
  and much more on a DAV-enabled webserver.
endef

DISTFILES += CSWpmhttpdav.gspec

DEPENDS += lib/neon cpan/libwww-perl cpan/XML-DOM

include gar/category.mk
