GARNAME = render
GARVERSION = 0.8
CATEGORIES = lib

DESCRIPTION = X Render extension headers
define BLURB
  Part of the FreeDesktop.org project.
endef

# XXX: Obsolete
#MASTER_SITES = http://pdx.freedesktop.org/~xlibs/release/
#DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz

CONFIGURE_ARGS = $(DIRPATHS)

TEST_TARGET = check

include ../category.mk
