#!/sbin/sh
#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)http-apache2	1.2	04/11/11 SMI"
#

APACHE_HOME=/opt/csw/apache2
CONF_FILE=$APACHE_HOME/etc/apache2/httpd.conf
PIDFILE=$APACHE_HOME/var/run/apache2/httpd.pid

[ ! -f ${CONF_FILE} ] &&  exit 1

case "$1" in
start|startssl)
	/bin/rm -f ${PIDFILE}
	/bin/mkdir -p `dirname $PIDFILE`
    cmd=$1
    if [ "$cmd" == "startssl" ]; then
        cmd="$cmd -DSSL"
    fi
	;;
restart)
    cmd="restart"
    ;;
graceful)
	cmd="graceful"
	;;
stop)
	cmd="stop"
	;;
*)
	echo "Usage: $0 {start|startssl|stop|restart|graceful}"
	exit 1
	;;
esac

exec ${APACHE_HOME}/bin/apachectl $cmd 2>&1
