NAME = Bit-Vector
VERSION = 7.2
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ANDK

DESCRIPTION = Efficient bit vector, set of integers and big int math library
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the unknown license

PACKAGES += CSWpm-bit-vector
CATALOGNAME_CSWpm-bit-vector = pm_bit_vector
SPKG_DESC_CSWpm-bit-vector = Efficient bit vector, set of integers and big int math library
RUNTIME_DEP_PKGS_CSWpm-bit-vector += CSWpm-carp-clan
OBSOLETED_BY_CSWpm-bit-vector += CSWpmbitvec
CATALOGNAME_CSWpmbitvec = pm_bitvec_stub

include gar/category.mk
