GARNAME = Bit-Vector
GARVERSION = 7.1
CATEGORIES = cpan
AUTHOR = STBEY

DESCRIPTION = Efficient bit vector, set of integers and big int math library.
define BLURB
endef

PACKAGES = CSWpmbitvec
CATALOGNAME = pm_bitvec

include gar/category.mk
