NAME = Bit-Vector
VERSION = 7.1
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = STBEY

DESCRIPTION = Efficient bit vector, set of integers and big int math library.
define BLURB
endef

PACKAGES = CSWpmbitvec
CATALOGNAME = pm_bitvec

RUNTIME_DEP_PKGS = CSWpmcarpclan
BUILD_DEP_PKGS = CSWpmcarpclan

include gar/category.mk
