GARNAME = Crypt-CAST5_PP
GARVERSION = 1.03
CATEGORIES = cpan
AUTHOR = BOBMATH

DESCRIPTION = CAST5 block cipher in pure Perl
define BLURB
  This module provides a pure Perl implementation of the CAST5 block cipher.
  CAST5 is also known as CAST-128. It is a product of the CAST design
  procedure developed by C. Adams and S. Tavares.
endef

DISTFILES += CSWpmcryptcast5pp.gspec

include ../category.mk
