diff --speed-large-files --minimal -Nru nagios-plugins-1.4.13.orig/Makefile.in nagios-plugins-1.4.13/Makefile.in
--- nagios-plugins-1.4.13.orig/Makefile.in	2008-09-25 10:33:22.000000000 +0200
+++ nagios-plugins-1.4.13/Makefile.in	2009-02-03 21:53:58.207039758 +0100
@@ -1037,6 +1037,12 @@
 install-root:
 	cd plugins-root && $(MAKE) $@
 
+install-contrib:
+	tar cf contrib.tar contrib/
+	$(INSTALL) -d $(DESTDIR)$(docdir)
+	$(INSTALL) -m 644 contrib.tar $(DESTDIR)$(docdir)
+
+
 tap:
 	cd @TAP_DIR@ && $(MAKE)
 
@@ -1073,3 +1079,5 @@
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
+
+none:
