#!/bin/sh
#
# $Id$
#
# A workaround because of a Solaris 10 kernel bug:
# http://bugs.opensolaris.org/view_bug.do?bug_id=6268715

executable=`basename $0`
libexec="/opt/csw/libexec"
libexec_binary="${libexec}/${executable}"

if [ -r "${libexec_binary}" ]; then
  :
else
  echo "Can't read ${libexec_binary}"
  exit 1
fi

# The workaround itself:
LIBEV_FLAGS=1
export LIBEV_FLAGS

exec "${libexec_binary}" "$@"
