#!/bin/sh

#RC_KNUM 72
#RC_SNUM 72
#RC_KLEV 0,1,S
#RC_SLEV 2
#FMRI network

case "$1" in
  start)
    echo "Starting unbound"

    if [ -x /usr/lib/extendedFILE.so.1 ]; then
       ulimit -n 1024
       LD_PRELOAD_32=/usr/lib/extendedFILE.so.1
       export LD_PRELOAD_32
    fi

    /opt/csw/sbin/unbound
    ;;
  stop)
    echo "Stopping unbound"
    kill `cat /var/run/unbound.pid` && rm /var/run/unbound.pid
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 { start | stop | restart }"
    exit 1
    ;;
esac

exit 0
