# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = twitter
VERSION = 1.6.1
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Twitter API, command-line tool, and IRC bot
define BLURB
  Long description
endef

DISTFILES  = $(DISTNAME).tar.gz
PACKAGES = CSWpy-twittertools
CATALOGNAME = py_twittertools
ARCHALL = 1

include gar/category.mk

