NAME = Time-Duration-Parse
VERSION = 0.06
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MIYAGAWA

DESCRIPTION = Parse string that represents time duration
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

BUILD_DEP_PKGS += CSWpm-time-duration

PACKAGES += CSWpm-time-duration-parse
CATALOGNAME_CSWpm-time-duration-parse = pm_time_duration_parse
SPKG_DESC_CSWpm-time-duration-parse = Parse string that represents time duration
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-time-duration-parse = 1
RUNTIME_DEP_PKGS_CSWpm-time-duration-parse += CSWpm-exporter-lite

include gar/category.mk
