PHP5EXT_NAME = exif

PACKAGES += CSWphp5exif

CATALOGNAME_CSWphp5exif = php5_exif
SPKG_DESC_CSWphp5exif = exif Extention for PHP5
REQUIRED_PKGS_CSWphp5exif = CSWphp5

CONFIGURE_ARGS += --enable-exif=shared

CPPFLAGS="-I../ext/mbstring"
export CPPFLAGS

PKGFILES_CSWphp5exif = .*/lib/php/extensions/.*/exif.*
