GARNAME = xine-ui
GARVERSION = 0.9.23
CATEGORIES = gnome

DESCRIPTION = Xine media player user interface.
define BLURB
    # Blurb goes here
endef

MASTER_SITES = http://aleron.dl.sourceforge.net/sourceforge/xine/
DISTFILES = $(GARNAME)-$(GARVERSION).tar.gz 

LIBDEPS = lib/xine-lib

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
