NAME = Test-XML
VERSION = 0.07
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = SEMANTICO

DESCRIPTION = Compare XML in perl tests
define BLURB
	This module contains generic XML testing tools. See below for a list of
	other modules with functions relating to specific XML modules.
endef

DISTFILES += $(call admfiles,CSWpmtestxml,depend prototype)

DEPENDS += cpan/XML-Parser
DEPENDS += cpan/XML-SemanticDiff

include gar/category.mk
