NAME = Devel-Trace
VERSION = 0.10
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MJD

DESCRIPTION = print out each line before it is executed
define BLURB
  If you run your program with perl -d:Trace program, this module will print a
  message to standard error just before each line is executed.
endef

DISTFILES += CSWpmdeveltrace.gspec

include gar/category.mk
