# $Id$
NAME = pydns
VERSION = 2.3.6
CATEGORIES = python
GARTYPE = v2

DESCRIPTION = Python DNS library

DISTFILES  = $(DISTNAME).tar.gz
SPKG_SOURCEURL = https://pypi.python.org/pypi/pydns
PACKAGES = CSWpy-dns

ARCHALL = 1
TEST_SCRIPTS =

include gar/category.mk
