NAME = TermReadKey
VERSION = 2.30
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JSTOWE

DESCRIPTION = Read keystrokes and change terminal modes
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the  license

PACKAGES += CSWpm-term-readkey
CATALOGNAME_CSWpm-term-readkey = pm_term_readkey
SPKG_DESC_CSWpm-term-readkey = Read keystrokes and change terminal modes
OBSOLETED_BY_CSWpm-term-readkey += CSWpmtermreadkey
CATALOGNAME_CSWpmtermreadkey = pm_termreadkey_stub

include gar/category.mk
