GARNAME = Apache-DBI
GARVERSION = 0.94
CATEGORIES = cpan
AUTHOR = ABH

DESCRIPTION = initiate a persistent database connection
define BLURB
  This module initiates a persistent database connection.
endef

DISTFILES += CSWpmapachedbi.gspec CSWpmapachedbi.depend

DEPENDS += cpan/DBI

# Tests require MySQL to be running
ENABLE_TEST = 0

include ../category.mk
