NAME = gettext
VERSION = 0.18.1.1
CATEGORIES = lib

DESCRIPTION = GNU locale utilities
define BLURB
	GNU gettext utilities are a set of tools that provides a framework to help other GNU packages produce multi-lingual messages
endef

PACKAGES += CSWggettext
PACKAGES += CSWggettextdoc
PACKAGES += CSWlibasprintf0
PACKAGES += CSWlibgettextlib0-14-1
PACKAGES += CSWlibgettextlib0-17
PACKAGES += CSWlibgettextlib0-18-1
PACKAGES += CSWlibgettextpo0
PACKAGES += CSWlibgettextsrc0-17
PACKAGES += CSWlibgettextsrc0-18-1
PACKAGES += CSWlibintl2
PACKAGES += CSWlibintl3
PACKAGES += CSWlibintl8
PACKAGES += CSWlibgettextlib0-18-1
PACKAGES += CSWggettext-dev
PACKAGES += CSWggettext-data

CATALOGNAME_CSWlibasprintf0 = libasprintf0
CATALOGNAME_CSWggettext = ggettext
CATALOGNAME_CSWggettext = ggettextdoc
CATALOGNAME_CSWlibgettextlib0-14-1 = libgettextlib0_14_1
CATALOGNAME_CSWlibgettextlib0-17 = libgettextlib0_17
CATALOGNAME_CSWlibgettextlib0-18-1 = libgettextlib0_18_1
CATALOGNAME_CSWlibgettextpo0 = libgettextpo0
CATALOGNAME_CSWlibgettextsrc0-17 = libgettextsrc0_17
CATALOGNAME_CSWlibgettextsrc0-18-1 = libgettextsrc0_18_1
CATALOGNAME_CSWlibintl2 = libintl2
CATALOGNAME_CSWlibintl3 = libintl3
CATALOGNAME_CSWlibintl8 = libintl8
CATALOGNAME_CSWlibgettextlib0-18-1 = libgettextlib0_18_1
CATALOGNAME_CSWggettext-dev = ggettext_dev
CATALOGNAME_CSWggettext-data = ggettext_data

SPKG_DESC_CSWggettext = GNU locale utilities
SPKG_DESC_CSWggettextdoc = GNU locale utility documentation
SPKG_DESC_CSWlibasprintf0 += GNU locale utilities, libasprintf.so.0
SPKG_DESC_CSWggettext-dev = GNU locale utilities, development files
SPKG_DESC_CSWlibgettextlib0-17 += GNU locale utilities, libgettextlib-0.17.so
SPKG_DESC_CSWlibgettextlib0-18-1 += GNU locale utilities, libgettextlib-0.18.1.so
SPKG_DESC_CSWlibgettextpo0 += GNU locale utilities, libgettextpo.so.0
SPKG_DESC_CSWlibgettextsrc0-17 += GNU locale utilities, libgettextsrc-0.17.so
SPKG_DESC_CSWlibgettextsrc0-18-1 += GNU locale utilities, libgettextsrc-0.18.1.so
SPKG_DESC_CSWlibintl2 += GNU locale utilities, libintl.so.2
SPKG_DESC_CSWlibintl3 += GNU locale utilities, libintl.so.3
SPKG_DESC_CSWlibintl8 += GNU locale utilities, libintl.so.8
SPKG_DESC_CSWlibgettextlib0-18-1 += GNU locale utilities, libgettextlib-0.18.1.so
SPKG_DESC_CSWggettext-data += GNU locale utilities, translation files

RUNTIME_DEP_PKGS_CSWlibgettextlib0-17 += CSWncurses
RUNTIME_DEP_PKGS_CSWlibgettextlib0-17 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextlib0-17 += CSWlibintl8
RUNTIME_DEP_PKGS_CSWlibgettextlib0-14-1 += CSWlibintl3
RUNTIME_DEP_PKGS_CSWlibgettextlib0-14-1 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWncurses
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWlibxml2
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWiconv
RUNTIME_DEP_PKGS_CSWggettext += CSWlibgettextlib0-18-1
RUNTIME_DEP_PKGS_CSWggettext += CSWlibgettextlib0-17
RUNTIME_DEP_PKGS_CSWlibgettextpo0 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextpo0 += CSWlibintl8
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-17 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-17 += CSWlibgettextlib0-17
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-17 += CSWlibintl8
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-18-1 += CSWlibintl8
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-18-1 += CSWncurses
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-18-1 += CSWlibxml2
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-18-1 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextsrc0-18-1 += CSWlibgettextlib0-18-1
RUNTIME_DEP_PKGS_CSWggettext += CSWlibgettextsrc0-18-1
RUNTIME_DEP_PKGS_CSWlibintl2 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibintl3 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibintl8 += CSWiconv
RUNTIME_DEP_PKGS_CSWggettext += CSWlibintl8
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWncurses
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWlibxml2
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWiconv
RUNTIME_DEP_PKGS_CSWlibgettextlib0-18-1 += CSWlibintl8
RUNTIME_DEP_PKGS_CSWggettext += CSWlibgettextlib0-18-1
RUNTIME_DEP_PKGS_CSWggettext-dev += CSWlibintl8
RUNTIME_DEP_PKGS_CSWggettext-dev += CSWlibasprintf0
RUNTIME_DEP_PKGS_CSWggettext-dev += CSWlibgettextsrc0-18-1
RUNTIME_DEP_PKGS_CSWggettext-dev += CSWlibgettextlib0-18-1
RUNTIME_DEP_PKGS_CSWggettext-dev += CSWlibgettextpo0

PKGFILES_CSWlibgettextlib0-18-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.18\.1\.so)
PKGFILES_CSWlibgettextlib0-18-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.18\.1\.so(\.\d+)*)
PKGFILES_CSWlibgettextpo0 += $(call baseisadirs,$(libdir),libgettextpo\.so\.0\.4\.0)
PKGFILES_CSWlibgettextpo0 += $(call baseisadirs,$(libdir),libgettextpo\.so\.0(\.\d+)*)
PKGFILES_CSWlibgettextpo0 += $(call baseisadirs,$(libdir),libgettextpo\.so\.0\.5\.1)
PKGFILES_CSWlibgettextsrc0-17 += $(call baseisadirs,$(libdir),libgettextsrc-0\.17\.so)
PKGFILES_CSWlibgettextsrc0-17 += $(call baseisadirs,$(libdir),libgettextsrc-0\.17\.so(\.\d+)*)
PKGFILES_CSWlibgettextsrc0-18-1 += $(call baseisadirs,$(libdir),libgettextsrc-0\.18\.1\.so)
PKGFILES_CSWlibgettextsrc0-18-1 += $(call baseisadirs,$(libdir),libgettextsrc-0\.18\.1\.so(\.\d+)*)
PKGFILES_CSWlibintl2 += $(call baseisadirs,$(libdir),libintl\.so\.2)
PKGFILES_CSWlibintl2 += $(call baseisadirs,$(libdir),libintl\.so\.2(\.\d+)*)
PKGFILES_CSWlibintl3 += $(call baseisadirs,$(libdir),libintl\.so\.3)
PKGFILES_CSWlibintl3 += $(call baseisadirs,$(libdir),libintl\.so\.3(\.\d+)*)
PKGFILES_CSWlibintl8 += $(call baseisadirs,$(libdir),libintl\.so\.8\.0\.2)
PKGFILES_CSWlibintl8 += $(call baseisadirs,$(libdir),libintl\.so\.8\.1\.1)
PKGFILES_CSWlibintl8 += $(call baseisadirs,$(libdir),libintl\.so\.8(\.\d+)*)
PKGFILES_CSWlibgettextlib0-18-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.18\.1\.so)
PKGFILES_CSWlibgettextlib0-18-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.18\.1\.so(\.\d+)*)
PKGFILES_CSWlibasprintf0 += $(call baseisadirs,$(libdir),libasprintf\.so\.0\.0\.0)
PKGFILES_CSWlibasprintf0 += $(call baseisadirs,$(libdir),libasprintf\.so\.0(\.\d+)*)
PKGFILES_CSWlibgettextlib0-14-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.14\.1\.so)
PKGFILES_CSWlibgettextlib0-14-1 += $(call baseisadirs,$(libdir),libgettextlib-0\.14\.1\.so(\.\d+)*)
SPKG_DESC_CSWlibgettextlib0-14-1 += GNU locale utilities, libgettextlib-0.14.1.so
PKGFILES_CSWlibgettextlib0-17 += $(call baseisadirs,$(libdir),libgettextlib-0\.17\.so)
PKGFILES_CSWlibgettextlib0-17 += $(call baseisadirs,$(libdir),libgettextlib-0\.17\.so(\.\d+)*)
PKGFILES_CSWggettext-dev += /opt/csw/lib/libasprintf.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/libgettextlib.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/libgettextpo.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/libgettextsrc.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/libintl.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/sparcv9/libasprintf.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/sparcv9/libgettextlib.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/sparcv9/libgettextpo.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/sparcv9/libgettextsrc.so
PKGFILES_CSWggettext-dev += /opt/csw/lib/sparcv9/libintl.so
PKGFILES_CSWggettext-data += /opt/csw/share/locale/.*mo

CHECKPKG_OVERRIDES_CSWggettextdoc += missing-dependency|CSWperl
CHECKPKG_OVERRIDES_CSWggettextdoc += missing-dependency|CSWggettext

ARCHALL_CSWggettextdoc = 1

COMPILE_ELISP = 1

MASTER_SITES = $(GNU_MIRROR)

DISTFILES  = $(NAME)-$(VERSION).tar.gz

PATCHFILES += 0001-Use-the-auto-detected-SHELL-to-run-convert-archive.patch
PATCHFILES += 0002-Update-ltmain.sh-to-prevent-libtool-stripping-runpat.patch

CONFIGURE_ARGS  = $(DIRPATHS)
CONFIGURE_ARGS += --program-prefix=g
#Dont' depend on packages that depend on me
CONFIGURE_ARGS += --with-included-glib
CONFIGURE_ARGS += --with-included-libcroco
#No glibc
CONFIGURE_ARGS += --with-included-gettext

UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz

BUILD64 = 1
NOISAEXEC = 1
STRIP_LIBTOOL = 1

RUNTIME_DEP_PKGS_CSWggettextdoc = CSWggettext

PKGFILES_CSWggettextdoc = $(PKGFILES_DOC)

#NOTE: gettext tests are sensitive to bash environment variables, make sure
#      custom paths are prefixed by $PATH, may be better to set aside
#      ~/.bashrc, etc. during build.
TEST_TARGET = check

#provided by iconv
MERGE_EXCLUDE_FILES  = .*/charset.alias
MERGE_EXCLUDE_FILES += .*/locale.alias
MERGE_EXCLUDE_FILES += .*/iconv.m4
MERGE_EXCLUDE_FILES += /opt/csw/bin/$(ISA)/.*

SHELL = /bin/bash

include gar/category.mk

PATH := /opt/csw/gnu:$(PATH)

#Include old libraries for compatibility with existing packages
#  TODO: Convert to modulated builds
post-install-isa-sparcv8:
	@mkdir $(INSTALLISADIR)/opt/csw/share/java
	@mv $(INSTALLISADIR)/opt/csw/share/gettext/libintl.jar $(INSTALLISADIR)/opt/csw/share/java
	@( for f in $(FILEDIR)/*.s; do gcp $$f $(INSTALLISADIR)/opt/csw/lib/$$(gbasename $$f .s); done )
	$(MAKECOOKIE)

post-install-isa-sparcv9:
	@rm $(INSTALLISADIR)/opt/csw/share/gettext/libintl.jar
	@( for f in $(FILEDIR)/*.s9; do gcp $$f $(INSTALLISADIR)/opt/csw/lib/$$(gbasename $$f .s9); done )
	$(MAKECOOKIE)

post-install-isa-i386:
	@mkdir $(INSTALLISADIR)/opt/csw/share/java
	@mv $(INSTALLISADIR)/opt/csw/share/gettext/libintl.jar $(INSTALLISADIR)/opt/csw/share/java
	@( for f in $(FILEDIR)/*.i; do gcp $$f $(INSTALLISADIR)/opt/csw/lib/$$(gbasename $$f .i); done )
	$(MAKECOOKIE)

post-install-isa-amd64:
	@rm $(INSTALLISADIR)/opt/csw/share/gettext/libintl.jar
	@( for f in $(FILEDIR)/*.amd64; do gcp $$f $(INSTALLISADIR)/opt/csw/lib/$$(gbasename $$f .amd64); done )
	$(MAKECOOKIE)

post-merge:
	@(cd $(PKGROOT)$(docdir); \
		find . -type f -print0 | xargs -0 perl -pi -e "s#/usr/share#/opt/csw/share#g" )
