NAME = libxml-perl
VERSION = 0.08
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = KMACLEOD

DESCRIPTION = 
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the  license

PACKAGES += CSWpm-libxml-perl
SPKG_DESC_CSWpm-libxml-perl = Perl SAX parser using XML::Parser
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-libxml-perl = 1
OBSOLETED_BY_CSWpm-libxml-perl += CSWpmlibxmlperl
CATALOGNAME_CSWpmlibxmlperl = pm_libxmlperl_stub

include gar/category.mk
