PHP5EXT_NAME = bcmath

PACKAGES += CSWphp5bcmath

CATALOGNAME_CSWphp5bcmath = php5_bcmath
SPKG_DESC_CSWphp5bcmath = bcmath Extention for PHP5
REQUIRED_PKGS_CSWphp5bcmath = CSWphp5

CONFIGURE_ARGS += --enable-bcmath=shared

PKGFILES_CSWphp5bcmath = .*/lib/php/extensions/.*/bcmath.*
