NAME = parallel-forkmanager
VERSION = 1.5.1
CATEGORIES = rbgems

DESCRIPTION = A simple parallel processing fork manager
define BLURB
endef

DISTFILES += COPYING
LICENSE = COPYING

PACKAGES = CSWgem-parallel-forkmanager
CATALOGNAME = gem_parallel_forkmanager

ARCHALL = 1

include gar/category.mk
