#!/bin/ksh
#
# phpext - PHP extension manager.
#

program=${0##*/}

# Default path to php.ini
php_ini=/opt/csw/php5/lib/php.ini

# Usage printer
function do_usage {

    # Print short usage
    cat << EOT
Usage: $program [-h] [-e|-d|-q] [-i <path>] <ext1>...<extN>
EOT

    # Print long usage
    if [ "$1" = "long" ]; then
        cat << EOT

Options:

    -e      Enable extensions
    -d      Disable extensions
    -q      Query mode
    -i      Path to php.ini (default: $php_ini)
    -h      Display usage information
    extN    Extension names

Examples:

    # Enable the exif and wddx extensions
    $program -e exif wddx

    # Disable xsl
    $program -d xsl

    # Check whether mbstring is enabled
    $program -q mbstring
    mbstring_enabled=true

    # Query all extensions from a different php.ini
    $program -i /path/to/php.ini -q

EOT
    fi

    exit 1
}

# Process command line options
typeset op
while getopts ":hedqi:" opts
do
    case ${opts} in
        e) op=enable ;;
        d) op=disable ;;
        i) php_ini=$OPTARG ;;
        q) op=query ;;
        h) do_usage "long" ;;
       \?) do_usage "long" ;;
    esac
done

shift $((${OPTIND} - 1 ))

if [ "$op" = "enable" ] || [ "$op" = "disable" ] && [ -z "$@" ]; then
    print "Error: No extensions specified for action $op"
    do_usage
fi

if [ ! -f $php_ini ]; then
    print "Error: Cannot access $php_ini"
    do_usage
fi

# In modes other than query, stream edit the file
typeset perlswitches php_extensions php_op
perlswitches="-lne"
if [ "$op" != "query" ]; then
    perlswitches="-i.bak -p $perlswitches"
fi

# Spawn perl to do the dirty work
export php_extensions="$@"
export php_op=$op
exec perl $perlswitches '
    BEGIN {
        use Config;
        use vars qw/$grabext $php_op/;
        $exts = $ENV{php_extensions}
            ? join("|", split(/\s+/, $ENV{php_extensions})) : qr{\S+};

        $grabext = qr{^(;)?extension=($exts)\.$Config{dlext}\s*$};
        $php_op  = $ENV{php_op};
    }
    if (my ($disabled, $extname) = $_ =~ $grabext) {
        if ($php_op eq "query") {
            printf "%s_enabled=%s\n", $extname, ($disabled ? "false" : "true");
        }
        elsif ($php_op eq "enable")  { s/^;// if     $disabled }
        elsif ($php_op eq "disable") { s/^/;/ unless $disabled }
    }' $php_ini

