GARNAME = Lingua-Stem
GARVERSION = 0.84
CATEGORIES = cpan
AUTHOR = SNOWHARE

DESCRIPTION = Stemming of words
define BLURB
endef

PACKAGES = CSWpmlinguastem
CATALOGNAME = pm_linguastem

LICENSE = LICENSE

DEP_PKGS  = CSWpmlinguaptstemmer
DEP_PKGS += CSWpmlinguastemfr
DEP_PKGS += CSWpmlinguastemit
DEP_PKGS += CSWpmlinguastemru
DEP_PKGS += CSWpmlinguastemsnoda
DEP_PKGS += CSWpmsnonorwegian
DEP_PKGS += CSWpmsnowballswedish
DEP_PKGS += CSWpmtextgerman

ARCHALL = 1

include gar/category.mk
