GARNAME = Lingua-Stem
GARVERSION = 0.84
CATEGORIES = cpan
AUTHOR = SNOWHARE

DESCRIPTION = Stemming of words
define BLURB
endef

PACKAGES = CSWpmlinguastem
CATALOGNAME = pm_linguastem

ARCHALL = 1

include gar/category.mk
