GARNAME = prawn-security
GARVERSION = 0.8.4
CATEGORIES = rbgems

DESCRIPTION = Popular Password Protection & Permissions for Prawn PDFs

define BLURB
  Prawn/Security ads document encryption, pasword protection, and
  permisions to Prawn. 
endef

GEMPKGNAME = prawnsecurity

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
