NAME = RADIUS-UserFile
VERSION = 1.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = OEVANS

DESCRIPTION = Perl RADIUS::UserFile module
define BLURB
  A module to manipulate information in a RADIUS users file.
endef

PACKAGES = CSWpmradiususerfile
CATALOGNAME = pm_radiususerfile

RUNTIME_DEP_PKGS = CSWpmtieixhash
BUILD_DEP_PKGS = $(RUNTIME_DEP_PKGS)

ARCHALL = 1

include gar/category.mk
