GARNAME = Snowball-Swedish
GARVERSION = 1.2
CATEGORIES = cpan
AUTHOR = ASKSH

DESCRIPTION = Porters stemming algorithm for Swedish
define BLURB
endef

PACKAGES = CSWpmsnowballswedish
CATALOGNAME = pm_snowballswedish

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
