# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = python-irclib
VERSION = 0.4.8
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Python IRC library
define BLURB
  Long description
endef

MASTER_SITES = $(SF_MIRRORS)
DISTFILES  = $(DISTNAME).tar.gz
LICENSE = COPYING

ARCHALL = 1

PACKAGES = CSWpy-irclib
CATALOGNAME = py_irclib

# No test suite available
TEST_SCRIPTS =

include gar/category.mk

