GARNAME = PerlIO-eol
GARVERSION = 0.13
CATEGORIES = cpan
AUTHOR = AUTRIJUS

DESCRIPTION = PerlIO layer for normalizing line endings
define BLURB
  This layer normalizes any of CR, LF, CRLF and Native into the designated
  line ending. It works for both input and output handles.
endef

PACKAGES = CSWpmperlioeol
CATALOGNAME = pm_perlioeol

ARCHALL = 1

include gar/category.mk
