NAME = Time-Period
VERSION = 1.23
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = PBOYD

DESCRIPTION = A Perl module to deal with time periods
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-time-period
CATALOGNAME_CSWpm-time-period = pm_time_period
SPKG_DESC_CSWpm-time-period = A Perl module to deal with time periods
ARCHALL_CSWpm-time-period = 1
OBSOLETED_BY_CSWpm-time-period += CSWpmtimeperiod
CATALOGNAME_CSWpmtimeperiod = pm_timeperiod_stub

include gar/category.mk
