NAME = Period
VERSION = 1.20
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = PRYAN

DESCRIPTION = A Perl module to deal with time periods
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmtimeperiod
CATALOGNAME = pm_timeperiod

ARCHALL = 1

include gar/category.mk
