PHP5EXT_NAME = mssql

PACKAGES += CSWphp5mssql

CATALOGNAME_CSWphp5mssql = php5_mssql
SPKG_DESC_CSWphp5mssql = mssql Extention for PHP5
REQUIRED_PKGS_CSWphp5mssql = CSWphp5 CSWfreetds

CONFIGURE_ARGS += --with-mssql=shared,$(prefix)

PKGFILES_CSWphp5mssql = .*/lib/php/extensions/.*/mssql.*
