NAME = Test-SharedFork
VERSION = 0.20
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = TOKUHIROM

DESCRIPTION = Fork test
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license, please see for details http://dev.perl.org/licenses/

BUILD_DEP_PKGS += CSWpm-test-requires

PACKAGES += CSWpm-test-sharedfork
CATALOGNAME_CSWpm-test-sharedfork = pm_test_sharedfork
SPKG_DESC_CSWpm-test-sharedfork = Fork test
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-sharedfork = 1

include gar/category.mk
