NAME = Object-MultiType
VERSION = 0.05
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GMPASSOS

DESCRIPTION = Perl Objects as Hash, Array, Scalar, Code and Glob at the same time

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the  license

PACKAGES += CSWpm-object-multitype
CATALOGNAME_CSWpm-object-multitype = pm_object_multitype
SPKG_DESC_CSWpm-object-multitype = Perl Objects as Hash, Array, Scalar, Code and Glob at the same time
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-object-multitype = 1
OBSOLETED_BY_CSWpm-object-multitype += CSWpmobjmultitype
CATALOGNAME_CSWpmobjmultitype = pm_objmultitype_stub

include gar/category.mk
