GARNAME = BSD-Resource
GARVERSION = 1.28
CATEGORIES = cpan
AUTHOR = JHI

DESCRIPTION = BSD process resource limit and priority functions
define BLURB
  BSD process resource limit and priority functions
endef

DISTFILES += CSWpmbsdresource.gspec

include gar/category.mk
