NAME = rspec-core
VERSION = 2.4.0
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = A Behaviour-Driven Development Tool

define BLURB
  RSpec runer and example groups
endef

LICENSE = License.txt

ARCHALL = 1

EXTRA_MERGE_EXCLUDE_FILES = .*/\.gitignore

include gar/category.mk
