NAME = enumerated_attribute
VERSION = 0.2.13
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = Enumerated model attributes and view helpers
define BLURB
  Enumerated model attributes and view helpers.
endef

PACKAGES = CSWgem-enumattr
CATALOGNAME = gem_enumattr

LICENSE = LICENSE

GEM_DEPS = CSWgem-metaprogr

ARCHALL = 1

include gar/category.mk
