NAME = Compress-Raw-Zlib
VERSION = 2.030
CATEGORIES = cpan
AUTHOR = PMQS

DESCRIPTION = Low-Level Interface to zlib compression library
define BLURB
  The Compress::Raw::Zlib module provides a Perl interface to the zlib
  compression library.
endef

DISTFILES += COPYING

CATALOGNAME = pm_compressrawzlib
PACKAGES = CSWpmcompressrawzlib

RUNTIME_DEP_PKGS += CSWzlib

EXTRA_MERGE_EXCLUDE_FILES = .*\/man\/man3.* .*\/man\/man1.*

include gar/category.mk
