GARNAME = HTML-Mason
GARVERSION = 1.42
CATEGORIES = cpan
AUTHOR = DROLSKY

DESCRIPTION = high-performance, dynamic web site authoring system
define BLURB
  Mason is a tool for building, serving and managing large web sites. Its
  features make it an ideal backend for high load sites serving dynamic
  content, such as online newspapers or database driven e-commerce sites.
endef

LICENSE = LICENSE

REQUIRED_PKGS = CSWpmcachecache CSWpmfcgi CSWpmclscontainer CSWpmexceptcls CSWpmprmsvldt CSWpmscalarlist

PACKAGES = CSWpmhtmlmason
CATALOGNAME = pm_htmlmason

ARCHALL = 1

include gar/category.mk
