GARNAME = IO-Tty
GARVERSION = 1.02
CATEGORIES = cpan
AUTHOR = RGIERSIG

DESCRIPTION = pseudo TTY object class
define BLURB
  IO::Pty provides an interface to allow the creation of a pseudo tty.
endef

DISTFILES += CSWpmiotty.gspec

include ../category.mk
