NAME = AutoXS-Header
VERSION = 1.02
CATEGORIES = cpan
AUTHOR = SMUELLER

DESCRIPTION = Container for the AutoXS header files
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmautoxsheader
CATALOGNAME = pm_autoxsheader

ARCHALL = 1

include gar/category.mk
