.TH "autossh" "1" "Jun 2009" "" ""

.PP
.SH "Please note"

.PP
The upstream \fBautossh\fP man page currently doesn't display properly on Solaris 
systems. For the time being, you can find the preformatted man page content under

.PP
/opt/csw/share/doc/autossh/autossh.1.txt

.PP
Use a pager of your choice (less, more, ...) to display it.
