NAME = redcloth
VERSION = 4.2.3
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = Textile parser for Ruby

define BLURB
endef

GEMNAME = RedCloth
DISTNAME = $(GEMNAME)-$(VERSION)
GEMPKGNAME = redcloth

LICENSE = COPYING

include gar/category.mk
