GARNAME = Net-Z3950-ZOOM
GARVERSION = 1.26
CATEGORIES = cpan
AUTHOR = MIRK

DESCRIPTION = Perl extension for invoking the ZOOM-C API
define BLURB
endef

PACKAGES = CSWpmnetz3950zoom
CATALOGNAME = pm_netz3950zoom

DEP_PKGS = CSWpmmarcrecord

include gar/category.mk
