NAME = Test-Tester
VERSION = 0.108
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = FDALY

DESCRIPTION = 
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = ARTISTIC

PACKAGES += CSWpm-test-tester
CATALOGNAME_CSWpm-test-tester = pm_test_tester
SPKG_DESC_CSWpm-test-tester = Ease testing test modules built with Test::Builder
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-tester = 1
OBSOLETED_BY_CSWpm-test-tester += CSWpmtesttester
CATALOGNAME_CSWpmtesttester = pm_testtester_stub

include gar/category.mk
