GARNAME = Test-Tester
GARVERSION = 0.107
CATEGORIES = cpan
AUTHOR = FDALY

DESCRIPTION = Ease testing test modules built with Test::Builder
define BLURB
  Ease testing test modules built with Test::Builder
endef

PACKAGES = CSWpmtesttester
CATALOGNAME = pm_testtester
ARCHALL = 1

LICENSE = ARTISTIC

include gar/category.mk
