NAME = Test-Script
VERSION = 1.03
CATEGORIES = cpan
AUTHOR = ADAMK

DESCRIPTION = Cross-platform basic tests for scripts
define BLURB
endef

RUNTIME_DEP_PKGS = CSWpmipcrun3

PACKAGES = CSWpmtestscript
CATALOGNAME = pm_testscript

ARCHALL = 1

include gar/category.mk
