# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = pyxdg
VERSION = 0.19
CATEGORIES = python

DESCRIPTION = Python library to access freedesktop.org standards
define BLURB
endef

VENDOR_URL   = http://www.freedesktop.org/wiki/Software/pyxdg
MASTER_SITES = http://www.freedesktop.org/~lanius/
DISTFILES    = $(DISTNAME).tar.gz
DISTFILES    = changelog.CSW

ARCHALL = 1

TEST_SCRIPTS =

include gar/category.mk
