NAME = Convert-BinHex
VERSION = 1.119
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ERYQ

DESCRIPTION = Perl module to extract data from Macintosh BinHex files
define BLURB
endef

PACKAGES = CSWpm-convert-binhex
CATALOGNAME = pm_convert_binhex
SPKG_DESC_CSWpm-convert-binhex = $(DESCRIPTION)
OBSOLETED_BY_CSWpm-convert-binhex = CSWpmconvertbinhex
CATALOGNAME_CSWpmconvertbinhex = pm_convertbinhex

ARCHALL = 1

SKIPTEST = 1

include gar/category.mk
