# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = Pillow
VERSION = 2.3.0
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Python Imaging Library (fork)
define BLURB
  Pillow is the "friendly" PIL fork by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
endef

DISTFILES  = $(DISTNAME).zip

PACKAGES += CSWpy-pillow

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk

