GARNAME = kdeaccessibility
CATEGORIES = kde

DESCRIPTION = Accessibility apps for KDE environment (gcc3)
define BLURB
  LONG DESCRIPTION
endef

DISTFILES += $(call admfiles,CSWkdeaccessgcc,)

DEPENDS += kde/arts lib/qt-gcc

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk
