NAME = Test-Differences
VERSION = 0.61
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = OVID

DESCRIPTION = Test strings and data structures and show differences if not ok
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = README

PACKAGES += CSWpm-test-differences
CATALOGNAME_CSWpm-test-differences = pm_test_differences
SPKG_DESC_CSWpm-test-differences = Test strings and data structures and show differences if not ok
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-differences = 1
RUNTIME_DEP_PKGS_CSWpm-test-differences += CSWpm-text-diff

include gar/category.mk
