NAME = Spreadsheet-WriteExcel
VERSION = 2.37
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JMCNAMARA

DESCRIPTION = Write to a cross platform Excel binary file
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-spreadsheet-writeexcel
CATALOGNAME_CSWpm-spreadsheet-writeexcel = pm_spreadsheet_writeexcel
SPKG_DESC_CSWpm-spreadsheet-writeexcel = Write to a cross platform Excel binary file
ARCHALL_CSWpm-spreadsheet-writeexcel = 1
RUNTIME_DEP_PKGS_CSWpm-spreadsheet-writeexcel += CSWpmparserecdescent
RUNTIME_DEP_PKGS_CSWpm-spreadsheet-writeexcel += CSWpmolestoragelite

include gar/category.mk
