# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id: Makefile 24024 2014-08-19 14:12:11Z cgrzemba $

NAME = oauth2client
VERSION = 1.4.9
CATEGORIES = python
GARTYPE = v2

DESCRIPTION = Google OAuth2Client
define BLURB
endef
# UFILES_REGEX = Django-(\d+(?:\.\d+)*).tar.gz


GIT_REPOS = http://github.com/google/$(NAME).git
# GIT_USE_PROXY = 1
# git@github.com:google/oauth2client.git
GIT_TREEISH_oauth2client.git = $(VERSION)


PACKAGES = CSWpy-oauth2client

include gar/category.mk

