GARNAME = pmtools
GARVERSION = 1.10
CATEGORIES = cpan
AUTHOR = MLFISHER

DESCRIPTION = Tools for managing installed Perl modules.
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmtools
CATALOGNAME = pmtools

ARCHALL = 1

include gar/category.mk
