NAME = IPC-ShareLite
VERSION = 0.17
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ANDYA

DESCRIPTION = Lightweight interface to shared memory
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-ipc-sharelite
CATALOGNAME_CSWpm-ipc-sharelite = pm_ipc_sharelite
SPKG_DESC_CSWpm-ipc-sharelite = Lightweight interface to shared memory
# There was no information if this is pure Perl or not. Please remove if necessary.
#ARCHALL_CSWpm-ipc-sharelite = 1
OBSOLETED_BY_CSWpm-ipc-sharelite += CSWpmipcshrlite
CATALOGNAME_CSWpmipcshrlite = pm_ipcshrlite_stub

include gar/category.mk
