GARNAME = Convert-UUlib
GARVERSION = 1.12
CATEGORIES = cpan
AUTHOR = MLEHMANN

DESCRIPTION = Perl interface to the uulib library
define BLURB
  Includes Convert::UUlib
endef

DISTFILES += $(call admfiles,CSWpmconvertuulib,)

include gar/category.mk
