NAME = Sort-Naturally
VERSION = 1.03
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = BINGOS

DESCRIPTION = Sort lexically, but sort numeral parts numerically
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-sort-naturally
CATALOGNAME_CSWpm-sort-naturally = pm_sort_naturally
SPKG_DESC_CSWpm-sort-naturally = Sort lexically, but sort numeral parts numerically
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-sort-naturally = 1
OBSOLETED_BY_CSWpm-sort-naturally += CSWpmsortnaturally
CATALOGNAME_CSWpmsortnaturally = pm_sortnaturally_stub

include gar/category.mk
