NAME = File-NFSLock
VERSION = 1.20
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = BBB

DESCRIPTION = Perl module to do NFS (or not) locking
define BLURB
  Program based of concept of hard linking of files being atomic across NFS.
  This concept was mentioned in Mail::Box::Locker (which was originally
  presented in Mail::Folder::Maildir).
endef

DISTFILES = $(call admfiles,CSWpmfilenfslock,depend prototype)

include gar/category.mk
