NAME = Digest
VERSION = stub
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GAAS

DESCRIPTION = Stub to the Perl build-in module Digest
define BLURB
endef

MODDIST =

PACKAGES = CSWpmdigest
CATALOGNAME = pm_digest

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =
TEST_SCRIPTS =
INSTALL_SCRIPTS =

ARCHALL = 1

# This package is completely empty, so it hasn't got any files
# and no license either.
CHECKPKG_OVERRIDES  = action-class-only-in-pkginfo|none
CHECKPKG_OVERRIDES += license-missing

include gar/category.mk
