NAME = Lingua-Stem-It
VERSION = 0.02
CATEGORIES = cpan
AUTHOR = ACALPINI

DESCRIPTION = Porter's stemming algorithm for Italian
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmlinguastemit
CATALOGNAME = pm_linguastemit

ARCHALL = 1

include gar/category.mk
