GARNAME = Unicode-Map
GARVERSION = 0.112
CATEGORIES = cpan
AUTHOR = MSCHWARTZ

DESCRIPTION = maps charsets from and to utf16 unicode
define BLURB
  This module converts strings from and to 2-byte Unicode UCS2 format. All
  mappings happen via 2 byte UTF16 encodings, not via 1 byte UTF8 encoding. To
  transform these use Unicode::String.
endef

DISTFILES += CSWpmunimap.gspec

include gar/category.mk
