GARNAME = Devel-Cycle
GARVERSION = 1.07
CATEGORIES = cpan
AUTHOR = LDS

DESCRIPTION = find memory cycles in objects
define BLURB
  This is a simple developer's tool for finding circular references in objects
  and other types of references. Because of Perl's reference-count based
  memory management, circular references will cause memory leaks.
endef

DISTFILES += CSWpmdevelcycle.gspec

include gar/category.mk
