GARNAME = Term-Cap
GARVERSION = 1.09
CATEGORIES = cpan
AUTHOR = JSTOWE

DESCRIPTION = termcap interface
define BLURB
  These are low-level functions to extract and use capabilities from a
  terminal capability (termcap) database.
endef

DISTFILES += CSWpmtermcap.gspec

include ../category.mk
