GARNAME = prawn-layout
GARVERSION = 0.8.4
CATEGORIES = rbgems

DESCRIPTION = An extension to Prawn that provides table support and other layout functionality

define BLURB
  An extension to Prawn that provides table suport and other layout
  functionality 
endef

DISTFILES = COPYING
LICENSE = COPYING

PACKAGES = CSWgem-prawn-layout
CATALOGNAME = gem_prawn_layout

ARCHALL = 1

include gar/category.mk
