NAME = Module-Build
VERSION = stub
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = EWILHELM

DESCRIPTION = Stub to the Perl build-in module Module::Build
define BLURB
endef

MODDIST =

PACKAGES = CSWpmmodulebuild
CATALOGNAME = pm_modulebuild

CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =
TEST_SCRIPTS =
INSTALL_SCRIPTS =

ARCHALL = 1

# This package is completely empty, so it hasn't got any files
# and no license either.
CHECKPKG_OVERRIDES  = action-class-only-in-pkginfo|none
CHECKPKG_OVERRIDES += license-missing

include gar/category.mk
