GARNAME = Proc-ProcessTable
GARVERSION = 0.41
CATEGORIES = cpan
AUTHOR = DURIST

DESCRIPTION = Perl interface to the unix process table
define BLURB
  Perl interface to the unix process table.
endef

DISTFILES += $(call admfiles,CSWpmproctbl,prototype)

include gar/category.mk
