GARNAME = Email-Simple
GARVERSION = 2.100
CATEGORIES = cpan
AUTHOR = RJBS

DESCRIPTION = Perl Email::Simple module for RFC2822 message format and headers
define BLURB
endef

REQUIRED_PKGS = CSWpmemaildateformat

PACKAGES = CSWpmemailsimple
CATALOGNAME = pm_emailsimple

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
