# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = txAMQP
VERSION = 0.6.2
CATEGORIES = python

DESCRIPTION = Python library for communicating with AMQP peers and brokers using Twisted

MASTER_SITES = $(PYPI_MIRROR)
DISTFILES += $(DISTNAME).tar.gz

PACKAGES += CSWpy-txamqp
SPKG_DESC_CSWpy-txamqp = Python library for communicating with AMQP peers and brokers using Twisted
# PKGFILES is catchall
ARCHALL_CSWpy-txamqp = 1

include gar/category.mk
