# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = textile
VERSION = 2.1.4
CATEGORIES = python
DESCRIPTION = XHTML generator using simple markup
define BLURB
endef
DISTFILES  = $(NAME)-$(VERSION).tar.gz
EXTRA_MERGE_EXCLUDE_FILES = .*/test\.py
CONFIGURE_ARGS = $(DIRPATHS)
TEST_SCRIPTS =
ARCHALL_CSWpy-textile = 1
include gar/category.mk
