PHP5EXT_NAME = sysvmsg

PACKAGES += CSWphp5sysvmsg

CATALOGNAME_CSWphp5sysvmsg = php5_sysvmsg
SPKG_DESC_CSWphp5sysvmsg = sysvmsg Extention for PHP5
REQUIRED_PKGS_CSWphp5sysvmsg = CSWphp5

CONFIGURE_ARGS += --enable-sysvsem=shared

PKGFILES_CSWphp5sysvmsg = .*/lib/php/extensions/.*/sysvmsg.*
