# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = scite
VERSION = 226
GARTYPE = v2
CATEGORIES = apps

DESCRIPTION = Text editor
define BLURB
  Long descriptECT = scintilla
MASTER_SITES = $(SF_MIRROR)
DISTFILES  = scite$(VERSION).tgz

include gar/category.mk

