GARNAME = UNIVERSAL-require
GARVERSION = 0.11
CATEGORIES = cpan
AUTHOR = MSCHWERN

DESCRIPTION = require modules from a variable
define BLURB
  get around the bareword caveats on require()
endef

DISTFILES += $(call admfiles,CSWpmunivrequire,depend prototype)

include ../category.mk
