NAME = DateTime-Locale
VERSION = 0.45
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DROLSKY

DESCRIPTION = Localization support for DateTime.pm
define BLURB
  DateTime::Locale is primarily a factory for the various locale subclasses. 
  It also provides some functions for getting information on all the available
  locales.
endef

PACKAGES = CSWpmdatetimelocale
CATALOGNAME = pm_datetimelocale

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk

