NAME = FCGI
VERSION = 0.73
CATEGORIES = cpan
AUTHOR = FLORA

DESCRIPTION = Fast CGI module
define BLURB
  Fast CGI module for Perl
endef

PACKAGES = CSWpmfcgi
CATALOGNAME = pm_fcgi

LICENSE = README

include gar/category.mk
