NAME = mysql
VERSION = 2.8.1
CATEGORIES = rbgems

DESCRIPTION = This is the MySQL API module for Ruby

define BLURB
  This is the MySQL API module for Ruby. It provides the same functionsfor Ruby programs that the MySQL C API provides for C programs. Thisis a conversion of tmtm's original extension into a proper RubyGems.
endef

RUNTIME_DEP_PKGS += CSWgem-rake-compiler
RUNTIME_DEP_PKGS += CSWgem-hoe

include gar/category.mk
