NAME = Class-Inspector
VERSION = 1.27
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ADAMK

DESCRIPTION = Get information about a class and its structure
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-class-inspector
CATALOGNAME_CSWpm-class-inspector = pm_class_inspector
SPKG_DESC_CSWpm-class-inspector = Get information about a class and its structure
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-class-inspector = 1
OBSOLETED_BY_CSWpm-class-inspector += CSWpmclassinspector
CATALOGNAME_CSWpmclassinspector = pm_classinspector_stub

include gar/category.mk
