GARNAME = Class-Inspector
GARVERSION = 1.24
CATEGORIES = cpan
AUTHOR = ADAMK

DESCRIPTION = Get information about a class and its structure
define BLURB
  Class::Inspector allows you to get information about a loaded class. Most or
  all of this information can be found in other ways, but they arn't always
  very friendly, and usually involve a relatively high level of Perl wizardry,
  or strange or unusual looking code. Class::Inspector attempts to provide an
  easier, more friendly interface to this information.
endef

LICENSE = LICENSE

PACKAGES = CSWpmclassinspector
CATALOGNAME = pm_classinspector

ARCHALL = 1

include gar/category.mk
