NAME = ExtUtils-Helpers
VERSION = 0.021
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = LEONT

DESCRIPTION = Various portability utilities for module builders
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-extutils-helpers
CATALOGNAME_CSWpm-extutils-helpers = pm_extutils_helpers
SPKG_DESC_CSWpm-extutils-helpers = Various portability utilities for module builders
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-extutils-helpers = 1

include gar/category.mk
