GARNAME = Net-IDN-Nameprep
GARVERSION = 1.000
CATEGORIES = cpan
AUTHOR = CFAERBER

DESCRIPTION = A Stringprep Profile for Internationalized Domain Names (RFC 3491)
define BLURB
  A Stringprep Profile for Internationalized Domain Names (RFC 3491)
endef

PACKAGES = CSWpmnetidnnameprep
CATALOGNAME = pm_netidnnameprep
ARCHALL = 1

LICENSE = LICENSE

# We define upstream file regex so we can be notifed of new upstream software release
UFILES_REGEX = $(GARNAME)-(\d+(?:\.\d+)*).tar.gz

include gar/category.mk
