NAME = IO-Digest
VERSION = 0.10
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CLKAO

DESCRIPTION = Calculate digests while reading or writing
define BLURB
  This module allows you to calculate digests while reading or writing file
  handles. This avoids the case you need to reread the same content to compute
  the digests after written a file.
endef

DISTFILES += COPYING

CATALOGNAME = pm_iodigest
PACKAGES = CSWpmiodigest

ARCHALL = 1

include gar/category.mk
