NAME = IO-Compress-Zlib
VERSION = 2.020
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = PMQS

DESCRIPTION = This is a stub, the contents has been integrated into CSWpmiocompress
define BLURB
endef

# This is a stub, the contents has been integrated into CSWpmiocompress
MODDIST =
CONFIGURE_SCRIPTS =
BUILD_SCRIPTS =
TEST_SCRIPTS =
INSTALL_SCRIPTS =

RUNTIME_DEP_PKGS = CSWpmiocompress

CATALOGNAME = pm_iocompresszlib
PACKAGES = CSWpmiocompresszlib

ARCHALL = 1

include gar/category.mk
