NAME = Test-TCP
VERSION = 1.15
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = TOKUHIROM

DESCRIPTION = Testing TCP program
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license, please see for details http://dev.perl.org/licenses/

PACKAGES += CSWpm-test-tcp
CATALOGNAME_CSWpm-test-tcp = pm_test_tcp
SPKG_DESC_CSWpm-test-tcp = Testing TCP program
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-tcp = 1
RUNTIME_DEP_PKGS_CSWpm-test-tcp += CSWpm-test-sharedfork

include gar/category.mk
