NAME = XML-Simple
VERSION = 2.20
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GRANTM

DESCRIPTION = Easily read/write XML (esp config files)
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-xml-simple
CATALOGNAME_CSWpm-xml-simple = pm_xml_simple
SPKG_DESC_CSWpm-xml-simple = Easily read/write XML (esp config files)
ARCHALL_CSWpm-xml-simple = 1
RUNTIME_DEP_PKGS_CSWpm-xml-simple += CSWpm-xml-sax
RUNTIME_DEP_PKGS_CSWpm-xml-simple += CSWpm-xml-sax-expat
RUNTIME_DEP_PKGS_CSWpm-xml-simple += CSWpm-xml-namespacesupport
OBSOLETED_BY_CSWpm-xml-simple += CSWpmxmlsimple
CATALOGNAME_CSWpmxmlsimple = pm_xmlsimple_stub

include gar/category.mk
