NAME = Net-HTTP
VERSION = 6.03
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GAAS

DESCRIPTION = Low-level HTTP connection (client)
define BLURB
  The Net::HTTP class is a low-level HTTP client. An instance of the Net::HTTP
  class represents a connection to an HTTP server. The HTTP protocol is
  described in RFC 2616. The Net::HTTP class supports HTTP/1.0 and HTTP/1.1.
endef

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES = CSWpm-net-http
CATALOGNAME = pm_net_http
ARCHALL = 1
RUNTIME_DEP_PKGS += CSWpm-compress-raw-zlib
RUNTIME_DEP_PKGS += CSWpm-io-compress

include gar/category.mk
