GARNAME = Algorithm-Annotate
GARVERSION = 0.10
CATEGORIES = cpan
AUTHOR = CLKAO

DESCRIPTION = represent a series of changes in annotate form
define BLURB
  Algorithm::Annotate generates a list that is useful for generating output
  simliar to cvs annotate.
endef

DISTFILES += CSWpmalgannotate.gspec CSWpmalgannotate.depend

DEPENDS += cpan/Algorithm-Diff

include ../category.mk
