GARNAME = kdetoys
CATEGORIES = kde

DESCRIPTION = Fun apps for KDE (gcc3)
define BLURB
  LONG DESCRIPTION
endef

DISTFILES += $(call admfiles,CSWkdetoysgcc,)

DEPENDS +=

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
