NAME = Proc-PID-File
VERSION = 1.27
GARTYPE = v2
CATEGORIES = cpan
AUTHOR = ECALDER

DESCRIPTION = Module to manage process id files
define BLURB
  Module to manage process id files
endef

LICENSE = LICENSE

#PACKAGING_PLATFORMS = solaris10-sparc solaris10-i386
PACKAGES = CSWpm-proc-pid-file
CATALOGNAME = pm_proc_pid_file
SPKG_DESC_CSWpm-proc-pid-file = $(DESCRIPTION)
ARCHALL = 1

# Name change
OBSOLETED_BY_CSWpm-proc-pid-file = CSWpm-proc-pid-files
CATALOGNAME_CSWpm-proc-pid-files = pm_proc_pid_files_stub

include gar/category.mk
