NAME = ar-extensions
VERSION = 0.9.2
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = Extends ActiveRecord functionality
define BLURB
  Extends ActiveRecord functionality by adding better finder/query support, as well as supporting mass data import,
  foreign key, CSV and temporary tables.
endef

PACKAGES = CSWgem-arextensions
CATALOGNAME = gem_arextensions

LICENSE = README

ARCHALL = 1

include gar/category.mk
