NAME = XML-Compile-Tester
VERSION = 0.90
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MARKOV

DESCRIPTION = Support XML::Compile related regression testing
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-xml-compile-tester
CATALOGNAME_CSWpm-xml-compile-tester = pm_xml_compile_tester
SPKG_DESC_CSWpm-xml-compile-tester = Support XML::Compile related regression testing
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-xml-compile-tester = 1
RUNTIME_DEP_PKGS_CSWpm-xml-compile-tester += CSWpm-log-report
RUNTIME_DEP_PKGS_CSWpm-xml-compile-tester += CSWpm-test-deep

include gar/category.mk
