NAME = Encode-JIS2K
VERSION = 0.02
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DANKOGAI

DESCRIPTION = JIS X 0212 (aka JIS 2000) Encodings

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-encode-jis2k
CATALOGNAME_CSWpm-encode-jis2k = pm_encode_jis2k
SPKG_DESC_CSWpm-encode-jis2k = JIS X 0212 (aka JIS 2000) Encodings

include gar/category.mk
