NAME = Biblio-EndnoteStyle
VERSION = 0.05
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MIRK

DESCRIPTION = Reference formatting using Endnote-like templates
define BLURB
  Reference formatting using Endnote-like templates
endef

DISTFILES += COPYING

PACKAGES = CSWpmbiblioendnotest
CATALOGNAME = pm_biblioendnotest
ARCHALL = 1

include gar/category.mk
