NAME = Test-Exception
VERSION = 0.29
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ADIE

DESCRIPTION = Test exception based code
define BLURB
  This module provides a few convenience methods for testing exception 
  based code. It is built with Test::Builder and plays happily with 
  Test::More and friends.
endef

PACKAGES = CSWpmtstexception
CATALOGNAME = pm_tstexception

ARCHALL = 1

LICENSE = $(FILEDIR)/LICENSE

include gar/category.mk
