NAME = Gtk2-TrayIcon
VERSION = 0.03
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MLEHMANN

DESCRIPTION = interface to the EggTrayIcon library
define BLURB
  This module allows a Perl developer to embed an arbitrary widget in a System
  Tray like the Gnome notification area.
endef

# Unstable branch
#MASTER_SITES = $(SF_MIRROR)/gtk2-perl/

DISTFILES += $(call admfiles,CSWpmgtk2trayicon,depend)

DEPENDS += cpan/Gtk2

include gar/category.mk
