#!/bin/sh
mv ./sql/mysqld ./cswstage/opt/csw/mysql5/libexec/mysqld32+
(cd libmysql_r/.libs ; tar cf - lib*so* ) | (cd cswstage/opt/csw/mysql5/lib/mysql/sparcv8plus+vis ; tar xf - )
(cd libmysql/.libs ; tar cf - lib*so* ) | (cd cswstage/opt/csw/mysql5/lib/mysql/sparcv8plus+vis ; tar xf - )
