NAME = Glib
VERSION = 1.304
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = XAOC

DESCRIPTION = Perl wrappers for the GLib utility and Object libraries
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-glib
CATALOGNAME_CSWpm-glib = pm_glib
SPKG_DESC_CSWpm-glib = Perl wrappers for the GLib utility and Object libraries
OBSOLETED_BY_CSWpm-glib += CSWpmglib
CATALOGNAME_CSWpmglib = pm_glib_stub

RUNTIME_DEP_PKGS_CSWpm-glib += CSWlibintl8
RUNTIME_DEP_PKGS_CSWpm-glib += CSWlibgobject2-0-0
RUNTIME_DEP_PKGS_CSWpm-glib += CSWlibglib2-0-0

include gar/category.mk
