GARNAME = Crypt-RIPEMD160
GARVERSION = 0.04
CATEGORIES = cpan
AUTHOR = CHGEUER

DESCRIPTION = Perl extension for the RIPEMD-160 Hash function
define BLURB
  The Crypt::RIPEMD160 module allows you to use the RIPEMD160 Message Digest
  algorithm from within Perl programs.
endef

DISTFILES = $(call admfiles,CSWpmcryptripemd160,depend prototype)

include ../category.mk
