GARNAME = SQL-Statement
GARVERSION = 1.15
CATEGORIES = cpan
AUTHOR = JZUCKER

DESCRIPTION = SQL parsing and processing engine
define BLURB
  The SQL::Statement module implements a small, abstract SQL engine.  This
  module is not usefull itself, but as a base class for deriving concrete SQL
  engines. The implementation is designed to work fine with the DBI driver
  DBD::CSV, thus probably not so well suited for a larger environment, but Id
  hope it is extendable without too much problems.
endef

DISTFILES += CSWpmsqlstatement.gspec

include gar/category.mk
