NAME = XML-Parser
VERSION = 2.41
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = TODDR

DESCRIPTION = A perl module for parsing XML documents
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-xml-parser
CATALOGNAME_CSWpm-xml-parser = pm_xml_parser
SPKG_DESC_CSWpm-xml-parser = A perl module for parsing XML documents
RUNTIME_DEP_PKGS_CSWpm-xml-parser += CSWpm-libwww-perl
RUNTIME_DEP_PKGS_CSWpm-xml-parser += CSWlibexpat1
OBSOLETED_BY_CSWpm-xml-parser += CSWpmxmlparser
CATALOGNAME_CSWpmxmlparser = pm_xmlparser_stub

include gar/category.mk
