NAME = Crypt-PasswdMD5
VERSION = 1.3
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = LUISMUNOZ

DESCRIPTION = Provides interoperable MD5-based crypt() functions
define BLURB
  Provides interoperable MD5-based crypt() functions
endef

DISTFILES += COPYING

PACKAGES = CSWpmcryptpasswdmd5
CATALOGNAME = pm_cryptpasswdmd5
ARCHALL = 1

include gar/category.mk
