NAME = Regexp-Shellish
VERSION = 0.93
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RBS

DESCRIPTION = Shell-like regular expressions
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the  license

PACKAGES += CSWpm-regexp-shellish
CATALOGNAME_CSWpm-regexp-shellish = pm_regexp_shellish
SPKG_DESC_CSWpm-regexp-shellish = Shell-like regular expressions
ARCHALL_CSWpm-regexp-shellish = 1
OBSOLETED_BY_CSWpm-regexp-shellish += CSWpmregexpshellish
CATALOGNAME_CSWpmregexpshellish = pm_regexpshellish_stub

include gar/category.mk
