GARNAME = MLDBM
GARVERSION = 2.01
CATEGORIES = cpan
AUTHOR = CHAMAS

DESCRIPTION = store multi-level hash structure in single level tied hash
define BLURB
  This module can serve as a transparent interface to any TIEHASH package that
  is required to store arbitrary perl data, including nested references. Thus,
  this module can be used for storing references and other arbitrary data
  within DBM databases.
endef

DISTFILES += CSWpmmldbm.gspec

include gar/category.mk
