NAME = MLDBM
VERSION = 2.04
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CHORNY

DESCRIPTION = Store multi-level hash structure in single level tied hash
define BLURB
  This module can serve as a transparent interface to any TIEHASH package that
  is required to store arbitrary perl data, including nested references. Thus,
  this module can be used for storing references and other arbitrary data
  within DBM databases.
endef

DISTFILES = COPYING

DEP_PKGS = CSWpmfreezethaw

PACKAGES = CSWpmmldbm
CATALOGNAME = pm_mldbm

ARCHALL = 1

include gar/category.mk
