PHP5EXT_NAME = gmp

PACKAGES += CSWphp5gmp

CATALOGNAME_CSWphp5gmp = php5_gmp
SPKG_DESC_CSWphp5gmp = gmp Extention for PHP5
REQUIRED_PKGS_CSWphp5gmp = CSWphp5 CSWlibgmp

CONFIGURE_ARGS += --with-gmp=shared,$(prefix)

PKGFILES_CSWphp5gmp = .*/lib/php/extensions/.*/gmp.*
