NAME = Sub-Uplevel
VERSION = 0.22
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DAGOLDEN

DESCRIPTION = Apparently run a function in a higher stack frame
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-sub-uplevel
CATALOGNAME_CSWpm-sub-uplevel = pm_sub_uplevel
SPKG_DESC_CSWpm-sub-uplevel = Apparently run a function in a higher stack frame
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-sub-uplevel = 1
OBSOLETED_BY_CSWpm-sub-uplevel += CSWpmsubuplevel
CATALOGNAME_CSWpmsubuplevel = pm_subuplevel_stub

include gar/category.mk
