NAME = Date-Manip
VERSION = 6.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = SBECK

DESCRIPTION = Date manipulation routines
define BLURB
  This is a set of routines designed to make any common date/time manipulation
  easy to do. Operations such as comparing two times, calculating a time a
  given amount of time from another, or parsing international times are all
  easily done.
endef

PACKAGES = CSWpmdatemanip
CATALOGNAME = pm_datemanip

ARCHALL = 1

include gar/category.mk
