GARNAME = version
GARVERSION = 0.7701
CATEGORIES = cpan
AUTHOR = JPEACOCK

DESCRIPTION = Perl extension for Version Objects
define BLURB
  Overloaded version objects for all modern versions of Perl. This module
  implements all of the features of version objects which will be part of Perl
  5.10.0.
endef

PACKAGES = CSWpmversion
CATALOGNAME = pm_version

include gar/category.mk
