NAME = Business-ISBN-Data
VERSION = 20081208
GARTYPE = v2
CATEGORIES = cpan
AUTHOR = BDFOY

DESCRIPTION = Data pack for Business::ISBN
define BLURB
  Data pack for Business::ISBN
endef

LICENSE = LICENSE

PACKAGES = CSWpm-business-isbn-data
CATALOGNAME = pm_business_isbn_data
ARCHALL = 1

CONFIGURE_ARGS =

include gar/category.mk

