NAME = Log-Dispatch
VERSION = 2.29
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DROLSKY

DESCRIPTION = Dispatches messages to one or more outputs
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-log-dispatch
CATALOGNAME_CSWpm-log-dispatch = pm_log_dispatch
SPKG_DESC_CSWpm-log-dispatch = Dispatches messages to one or more outputs
ARCHALL_CSWpm-log-dispatch = 1
RUNTIME_DEP_PKGS_CSWpm-log-dispatch += CSWpm-params-validate
OBSOLETED_BY_CSWpm-log-dispatch += CSWpmlogdispatch
CATALOGNAME_CSWpmlogdispatch = pm_logdispatch_stub

include gar/category.mk
