GARNAME = kdegraphics
GARVERSION = 3.5.0
CATEGORIES = kde

DESCRIPTION = Graphic utilities for KDE (gcc3)
define BLURB
  LONG DESCRIPTION
endef

DISTFILES += $(call admfiles,CSWkdegraphicsgcc,depend)

DEPENDS +=

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
