NAME = PerlIO-gzip
VERSION = 0.18
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = NWCLARK

DESCRIPTION = Perl extension to provide a PerlIO layer to gzip/gunzip
define BLURB
  A layer for the PerlIO system to transparently gzip/gunzip files.
  **DON'T** trust it with your data.
endef

RUNTIME_DEP_PKGS = CSWzlib

PACKAGES = CSWpmperliogzip
CATALOGNAME = pm_perliogzip

include gar/category.mk
