NAME = File-Slurp
VERSION = 9999.13
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DROLSKY

DESCRIPTION = Efficient Reading/Writing of Complete Files
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmfileslurp
CATALOGNAME = pm_fileslurp

ARCHALL = 1

include gar/category.mk
