GARNAME = Regexp-Common
GARVERSION = 2.120
CATEGORIES = cpan
AUTHOR = ABIGAIL

DESCRIPTION = provide commonly requested regular expressions
define BLURB
  By default, this module exports a single hash (%RE) that stores or generates
  commonly needed regular expressions (see "List of available patterns").
endef

DISTFILES += CSWpmregexpcom.gspec

# Beware -- Regexp::Common::numbers{square} may be flaky...
#PATCHFILES = disable_squares_t.diff

include gar/category.mk
