GARNAME = CGI.pm
GARVERSION = 3.27
CATEGORIES = cpan
AUTHOR = LDS

DESCRIPTION = simple common gateway interface class
define BLURB
  This perl library uses perl5 objects to make it easy to create Web fill-out
  forms and parse their contents. This package defines CGI objects, entities
  that contain the values of the current query string and other state
  variables.  Using a CGI object's methods, you can examine keywords and
  parameters passed to your script, and create forms whose initial values are
  taken from the current query (thereby preserving state information). The
  module provides shortcut functions that produce boilerplate HTML, reducing
  typing and coding errors. It also provides functionality for some of the
  more advanced features of CGI scripting, including support for file uploads,
  cookies, cascading style sheets, server push, and frames.
endef

DISTFILES = $(call admfiles,CSWpmcgi,depend prototype)

include ../category.mk
