NAME = Sub-Exporter-Progressive
VERSION = 0.001010
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = FREW

DESCRIPTION = Only use Sub::Exporter if you need it
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-sub-exporter-progressive
CATALOGNAME_CSWpm-sub-exporter-progressive = pm_sub_exporter_progressive
SPKG_DESC_CSWpm-sub-exporter-progressive = Only use Sub::Exporter if you need it
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-sub-exporter-progressive = 1

include gar/category.mk
