PHP5EXT_NAME = zlib

PACKAGES += CSWphp5zlib

CATALOGNAME_CSWphp5zlib = php5_zlib
SPKG_DESC_CSWphp5zlib = zlib Extention for PHP5
REQUIRED_PKGS_CSWphp5zlib = CSWphp5 CSWzlib

CONFIGURE_ARGS += --with-zlib=shared,$(prefix)

PKGFILES_CSWphp5zlib = .*/lib/php/extensions/.*/zlib.*
