NAME = Want
VERSION = 0.18
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ROBIN

DESCRIPTION = a generalisation of wantarray
define BLURB
  This module generalises the mechanism of the wantarray function, allowing a
  function to determine in some detail how its return value is going to be
  immediately used.
endef

PACKAGES = CSWpmwant
CATALOGNAME = pm_want

include gar/category.mk
