GARNAME = Class-Accessor
GARVERSION = 0.22
CATEGORIES = cpan
AUTHOR = KASEI

DESCRIPTION = automated accessor generation
define BLURB
  This module automagically generates accessor/mutators for your class.
endef

DISTFILES += CSWpmclassacc.gspec

include ../category.mk
