GARNAME = Class-Accessor
GARVERSION = 0.19
CATEGORIES = cpan
AUTHOR = KASEI
GARCH = all

DESCRIPTION = automated accessor generation
define BLURB
  This module automagically generates accessor/mutators for your class.
endef

DISTFILES += CSWpmclassacc.gspec

include ../category.mk
