GARNAME = I18N-LangTags
GARVERSION = 0.35
CATEGORIES = cpan
AUTHOR = SBURKE

DESCRIPTION = functions for dealing with RFC3066-style language tags
define BLURB
  Language tags are a formalism, described in RFC 3066 (obsoleting 1766), for
  declaring what language form (language and possibly dialect) a given chunk
  of information is in.  This library provides functions for common tasks
  involving language tags as they are needed in a variety of protocols and
  applications.
endef

DISTFILES += CSWpmi18nlangtags.gspec

include gar/category.mk
