NAME = MIME-tools
VERSION = 5.504
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DSKOLL

DESCRIPTION = MIME-Tools: Modules for parsing and creating MIME entities
define BLURB
  Modules for parsing (and creating!) MIME entities
endef

DEPENDS += cpan/Mail-Tools cpan/Convert-BinHex cpan/Unix-Syslog cpan/IO-stringy

PACKAGES = CSWpm-mime-tools
CATALOGNAME = pm_mime_tools
ARCHALL = 1

INCOMPATIBLE_PKGS_CSWpm-mime-tools = CSWpmmimetools

COPYING = LICENSE

# Temporary override for package rename
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/NBit.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Field/ConTraEnc.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Parser::Reader.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Parser.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/UU.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Head.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/WordDecoder.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Tools.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Parser/Results.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Parser::Filer.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Field/ParamVal.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::UU.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::Gzip64.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Field/ContType.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Parser.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Words.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::NBit.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/Binary.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::WordDecoder.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Field::ParamVal.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::Base64.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Head.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::BinHex.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Field::ContType.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::Binary.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Parser/Reader.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Body.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Entity.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/Gzip64.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Tools.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Body.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/QuotedPrint.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/Base64.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Field/ContDisp.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Field::ContDisp.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Words.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder/BinHex.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Decoder::QuotedPrint.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Field::ConTraEnc.3perl|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Decoder.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Entity.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/perl/csw/MIME/Parser/Filer.pm|CSWpm-mime-tools|CSWpmmimetools
CHECKPKG_OVERRIDES_CSWpm-mime-tools += file-collision|/opt/csw/share/man/man3/MIME::Parser::Results.3perl|CSWpm-mime-tools|CSWpmmimetools

include gar/category.mk
