GARNAME = MIME-tools
GARVERSION = 5.427
CATEGORIES = cpan
AUTHOR = ERYQ

DESCRIPTION = modules for parsing and creating MIME entities
define BLURB
  Modules for parsing (and creating!) MIME entities
endef

DISTFILES += $(call admfiles,CSWpmmimetools,depend)

DEPENDS += cpan/Mail-Tools cpan/Convert-BinHex cpan/Unix-Syslog

include gar/category.mk
