GARNAME = Text-Reform
GARVERSION = 1.11
CATEGORIES = cpan
AUTHOR = DCONWAY

DESCRIPTION = manual text wrapping and reformatting
define BLURB
endef

DISTFILES += CSWpmtxtreform.gspec

include gar/category.mk
