GARNAME = IO-Tty
GARVERSION = 1.07
CATEGORIES = cpan
AUTHOR = RGIERSIG

DESCRIPTION = pseudo TTY object class
define BLURB
  IO::Pty provides an interface to allow the creation of a pseudo tty.
endef

DISTFILES += CSWpmiotty.gspec

include gar/category.mk
