
# Package Definition File
PACKAGES  = CSWphp4bcmath CSWphp4bz2 CSWphp4calendar CSWphp4cgi CSWphp4curl
PACKAGES += CSWphp4dba CSWphp4domxml CSWphp4gd CSWphp4gettext CSWphp4gmp
PACKAGES += CSWphp4iconv CSWphp4imap CSWphp4ldap CSWphp4mbstring
PACKAGES += CSWphp4mcal CSWphp4mssql CSWphp4mysql CSWphp4ncurses CSWphp4odbc
PACKAGES += CSWphp4openssl CSWphp4pgsql CSWphp4zlib CSWap2modphp4
PACKAGES += CSWmodphp4 CSWphp

CATALOGNAME_CSWphp4bcmath = php4_bcmath
SPKG_DESC_CSWphp4bcmath = bcmath extension for php4
CATALOGNAME_CSWphp4bz2 = php4_bz2
SPKG_DESC_CSWphp4bz2 = bzip2 extension for php4
CATALOGNAME_CSWphp4calendar = php4_calendar
SPKG_DESC_CSWphp4calendar = calendar extension for php4
CATALOGNAME_CSWphp4cgi = php4_cgi
SPKG_DESC_CSWphp4cgi = command line interpreter for the PHP language
CATALOGNAME_CSWphp4curl = php4_curl
SPKG_DESC_CSWphp4curl = curl extension for php4
CATALOGNAME_CSWphp4dba = php4_dba
SPKG_DESC_CSWphp4dba = dba extension for php4
CATALOGNAME_CSWphp4domxml = php4_domxml
SPKG_DESC_CSWphp4domxml = domxml extension for php4
CATALOGNAME_CSWphp4gd = php4_gd
SPKG_DESC_CSWphp4gd = gd extension for php4
CATALOGNAME_CSWphp4gettext = php4_gettext
SPKG_DESC_CSWphp4gettext = gettext extension for php4
CATALOGNAME_CSWphp4gmp = php4_gmp
SPKG_DESC_CSWphp4gmp = gmp extension for php4
CATALOGNAME_CSWphp4iconv = php4_iconv
SPKG_DESC_CSWphp4iconv = iconv extension for php4
CATALOGNAME_CSWphp4imap = php4_imap
SPKG_DESC_CSWphp4imap = imap extension for php4
CATALOGNAME_CSWphp4ldap = php4_ldap
SPKG_DESC_CSWphp4ldap = ldap extension for php4
CATALOGNAME_CSWphp4mbstring = php4_mbstring
SPKG_DESC_CSWphp4mbstring = mbstring extension for php4
CATALOGNAME_CSWphp4mcal = php4_mcal
SPKG_DESC_CSWphp4mcal = modular calendar extension for php4
CATALOGNAME_CSWphp4mssql = php4_mssql
SPKG_DESC_CSWphp4mssql = mssql extension for php4
CATALOGNAME_CSWphp4mysql = php4_mysql
SPKG_DESC_CSWphp4mysql = mysql extension for php4
CATALOGNAME_CSWphp4ncurses = php4_ncurses
SPKG_DESC_CSWphp4ncurses = ncurses extension for php4
CATALOGNAME_CSWphp4odbc = php4_odbc
SPKG_DESC_CSWphp4odbc = odbc extension for php4
CATALOGNAME_CSWphp4openssl = php4_openssl
SPKG_DESC_CSWphp4openssl = openssl extension for php4
CATALOGNAME_CSWphp4pgsql = php4_pgsql
SPKG_DESC_CSWphp4pgsql = postgresql extension for php4
CATALOGNAME_CSWphp4zlib = php4_zlib
SPKG_DESC_CSWphp4zlib = zlib extension for php4
CATALOGNAME_CSWap2modphp4 = ap2_modphp4
SPKG_DESC_CSWap2modphp4 = PHP 4 - Apache 2.2.x Module
CATALOGNAME_CSWmodphp4 = mod_php4_core
SPKG_DESC_CSWmodphp4 = PHP 4 - Apache 1.3.x Module
CATALOGNAME_CSWphp = mod_php
SPKG_DESC_CSWphp = Both an apache module and command line interpreter for the PHP language
ARCHALL_CSWphp =  1
