# Copyright 2012 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = ordereddict
VERSION = 1.1
CATEGORIES = python
GARTYPE = v2

DESCRIPTION = A drop-in substitute for Python 2.7 new collections

DISTFILES = $(DISTNAME).tar.gz
VENDOR_URL = http://pypi.python.org/pypi/ordereddict/1.1
ARCHALL_CSWpy-$(NAME) = 1

# There is no testsuite
TEST_SCRIPTS =

MODULATIONS_PYTHON_VERSION = 2_6

include gar/category.mk
