NAME = Chart
VERSION = 2.4.6
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CHARTGRP

DESCRIPTION = Implements new Chart
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the unknown license

PACKAGES += CSWpm-chart
SPKG_DESC_CSWpm-chart = Implements new Chart
ARCHALL_CSWpm-chart = 1
RUNTIME_DEP_PKGS_CSWpm-chart += CSWpm-gd
OBSOLETED_BY_CSWpm-chart += CSWpmchart
CATALOGNAME_CSWpmchart = pm_chart_stub

include gar/category.mk
