GARNAME = Log-Log4perl
GARVERSION = 1.09
CATEGORIES = cpan
AUTHOR = MSCHILLI

DESCRIPTION = Log4j implementation for Perl
define BLURB
  Log::Log4perl lets you remote-control and fine-tune the logging behaviour of
  your system from the outside. It implements the widely popular (Java-based)
  Log4j logging package in pure Perl.
endef

DISTFILES += CSWpmlog4perl.gspec

include gar/category.mk
