# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = mechanize
VERSION = 0.2.4
CATEGORIES = python
DESCRIPTION = Stateful programmatic web browsing in Python
define BLURB
endef
SPKG_SOURCEURL = http://wwwsearch.sourceforge.net/mechanize/
MASTER_SITES = http://wwwsearch.sourceforge.net/$(NAME)/src/
DISTFILES  = $(NAME)-$(VERSION).tar.gz
UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz
include gar/category.mk
