NAME = Module-Signature
VERSION = 0.73
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = AUDREYT

DESCRIPTION = Module signature file manipulation
define BLURB
endef

PACKAGES = CSWpm-module-signature
CATALOGNAME = pm_module_signature
SPKG_DESC_CSWpm-module-signature = $(DESCRIPTION)

ARCHALL = 1

RUNTIME_DEP_PKGS += CSWgnupg
RUNTIME_DEP_PKGS += CSWpmpardist
RUNTIME_DEP_PKGS += CSWpm-text-diff

include gar/category.mk
