GARNAME = Module-Signature
GARVERSION = 0.54
CATEGORIES = cpan
AUTHOR = AUTRIJUS

DESCRIPTION = module signature file manipulation
define BLURB
  Module::Signature adds cryptographic authentications to CPAN distributions,
  via the special SIGNATURE file.
endef

DISTFILES += CSWpmmodulesignature.gspec CSWpmmodulesignature.depend

DEPENDS += cpan/Text-Diff cpan/Crypt-OpenPGP cpan/PAR-Dist

include ../category.mk
