NAME = List-MoreUtils
VERSION = 0.33
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ADAMK

DESCRIPTION = Provide the stuff missing in List::Util
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-list-moreutils
CATALOGNAME_CSWpm-list-moreutils = pm_list_moreutils
SPKG_DESC_CSWpm-list-moreutils = Provide the stuff missing in List::Util
OBSOLETED_BY_CSWpm-list-moreutils += CSWpmlistmoreutils
CATALOGNAME_CSWpmlistmoreutils = pm_listmoreutils_stub

include gar/category.mk
