NAME = Tie-IxHash
VERSION = 1.22
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = CHORNY

DESCRIPTION = Ordered associative arrays for Perl
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license, please see for details http://dev.perl.org/licenses/

PACKAGES += CSWpm-tie-ixhash
CATALOGNAME_CSWpm-tie-ixhash = pm_tie_ixhash
SPKG_DESC_CSWpm-tie-ixhash = Ordered associative arrays for Perl
ARCHALL_CSWpm-tie-ixhash = 1
OBSOLETED_BY_CSWpm-tie-ixhash += CSWpmtieixhash
CATALOGNAME_CSWpmtieixhash = pm_tieixhash_stub

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
TEST_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build

include gar/category.mk
