NAME = Tie-IxHash
VERSION = 1.21
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GSAR

DESCRIPTION = Ordered associative arrays for Perl
define BLURB
  This Perl module implements Perl hashes that preserve the order in which the
  hash elements were added. The order is not affected when values
  corresponding to existing keys in the IxHash are changed. The elements can
  also be set to any arbitrary supplied order. The familiar perl array
  operations can also be performed on the IxHash.
endef

PACKAGES = CSWpmtieixhash
CATALOGNAME = pm_tieixhash

ARCHALL = 1

include gar/category.mk
