GARNAME = Devel-Symdump
GARVERSION = 2.08
CATEGORIES = cpan
AUTHOR = ANDK

DESCRIPTION = Dump symbol names or the symbol table
define BLURB
  This little package serves to access the symbol table of perl.
endef

PACKAGES = CSWpmdevelsymdump
CATALOGNAME = pm_develsymdump

ARCHALL = 1

include gar/category.mk
