# $Id$
#
NAME = subvertpy
VERSION = 0.8.2
GARTYPE = v2
CATEGORIES = python

DESCRIPTION = Alternative python bindings for subversion

MASTER_SITES = http://launchpad.net/subvertpy/trunk/$(VERSION)/+download/
DISTFILES  = $(DISTNAME).tar.gz
#UPSTREAM_MASTER_SITES = http://launchpad.net/subvertpy/trunk

# File name regex to get notifications about upstream software releases
# NOTE: Use this only if the automatic regex creation
#       does not work for your package
# UFILES_REGEX = $(NAME)-(\d+(?:\.\d+)*).tar.gz

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk

