NAME = Test-LongString
VERSION = 0.15
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RGARCIA

DESCRIPTION = 
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES += CSWpm-test-longstring
CATALOGNAME_CSWpm-test-longstring = pm_test_longstring
SPKG_DESC_CSWpm-test-longstring = Tests strings for equality, with more helpful failures
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-longstring = 1
OBSOLETED_BY_CSWpm-test-longstring += CSWpmtestlongstr
CATALOGNAME_CSWpmtestlongstr = pm_testlongstr_stub

include gar/category.mk
