GARNAME = kdemultimedia
CATEGORIES = kde

DESCRIPTION = Multimedia apps for KDE (gcc3)
define BLURB
  LONG DESCRIPTION
endef

DISTFILES += $(call admfiles,CSWkdemultimediagcc,)

DEPENDS +=

CONFIGURE_ARGS = $(DIRPATHS)

include ../category.mk
