GARNAME = Net-SSH2
GARVERSION = 0.33
CATEGORIES = cpan
AUTHOR = RKITOVER

DESCRIPTION = Support for the SSH 2 protocol via libssh2
define BLURB
  Support for the SSH 2 protocol via libssh2
endef

DISTFILES += COPYING

PACKAGES = CSWpmnetssh2
CATALOGNAME = pm_netssh2

RUNTIME_DEP_PKGS_CSWpmnetssh2 += CSWosslrt CSWlibssh2 CSWzlib

include gar/category.mk
