NAME = DateTime-Format-Strptime
VERSION = 1.52
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DROLSKY

DESCRIPTION = Parse and format strp and strf time patterns
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-datetime-format-strptime
CATALOGNAME_CSWpm-datetime-format-strptime = pm_datetime_format_strptime
SPKG_DESC_CSWpm-datetime-format-strptime = Parse and format strp and strf time patterns
ARCHALL_CSWpm-datetime-format-strptime = 1
RUNTIME_DEP_PKGS_CSWpm-datetime-format-strptime += CSWpm-datetime
RUNTIME_DEP_PKGS_CSWpm-datetime-format-strptime += CSWpm-params-validate
RUNTIME_DEP_PKGS_CSWpm-datetime-format-strptime += CSWpm-datetime-locale
RUNTIME_DEP_PKGS_CSWpm-datetime-format-strptime += CSWpm-datetime-timezone

include gar/category.mk
