#!/sbin/sh

case "$1" in
  start)
    echo "Starting nsd."
    /opt/csw/sbin/nsd-control start
    ;;
  stop)
    echo "Stopping nsd."
    /usr/bin/kill -TERM `cat /var/run/nsd.pid`
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
    refresh)
    echo "Refreshing nsd."
    /usr/bin/kill -HUP `cat /var/run/nsd.pid`
    ;;
  *)
    echo "Usage: $0 { start | stop | restart | refresh }"
    exit 1
    ;;
esac

exit 0
