NAME = Class-XSAccessor
VERSION = 1.05
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = SMUELLER

DESCRIPTION = Generate fast XS accessors without runtime compilation
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmclassxsaccessor
CATALOGNAME = pm_classxsaccessor

include gar/category.mk
