# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = gwhois
VERSION = 20120626
GARTYPE = v2

DESCRIPTION = Brief description
define BLURB
  Long description
endef

MASTER_SITES = http://gwhois.de/gwhois
DISTNAME = $(NAME)_$(VERSION)
DISTFILES  = $(DISTNAME).tar.gz

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk

