GARNAME = kdeartwork
CATEGORIES = kde

DESCRIPTION = Additional artwork for KDE (gcc3)
define BLURB
  LONG DESCRIPTION
endef

DISTFILES += $(call admfiles,CSWkdeartworkgcc,)

DEPENDS +=

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk
