NAME = Module-Runtime
VERSION = 0.013
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ZEFRAM

DESCRIPTION = Runtime module handling
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the perl license, please see for details http://dev.perl.org/licenses/

PACKAGES += CSWpm-module-runtime
CATALOGNAME_CSWpm-module-runtime = pm_module_runtime
SPKG_DESC_CSWpm-module-runtime = Runtime module handling
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-module-runtime = 1

CONFIGURE_SCRIPTS = $(WORKSRC)/Build.PL
BUILD_SCRIPTS = $(WORKSRC)/Build
TEST_SCRIPTS = $(WORKSRC)/Build
INSTALL_SCRIPTS = $(WORKSRC)/Build

include gar/category.mk
