NAME = Tree-DAG_Node
VERSION = 1.11
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RSAVAGE

DESCRIPTION = Class for representing nodes in a tree
define BLURB
endef

DISTFILES += COPYING

MODDIST ?= $(DISTNAME).tgz

PACKAGES = CSWpm-tree-dag-node
CATALOGNAME = pm_tree_dag_node
SPKG_DESC_CSWpm-tree-dag-node = $(DESCRIPTION)
OBSOLETED_BY_CSWpm-tree-dag-node = CSWpmtreedagnode
CATALOGNAME_CSWpmtreedagnode = pm_treedagnode

ARCHALL = 1

include gar/category.mk
