NAME = Locale-Maketext-Simple
VERSION = 0.21
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JESSE

DESCRIPTION = Simple interface to Locale::Maketext::Lexicon
define BLURB
  This module is a simple wrapper around Locale::Maketext::Lexicon, designed
  to alleviate the need of creating Language Classes for module authors.
endef

DISTFILES += COPYING

PACKAGES = CSWpmlclemktxtsimple
CATALOGNAME = pm_lclemktxtsimple 
ARCHALL = 1

RUNTIME_DEP_PKGS = CSWpmlclemktxtlex

EXTRA_MERGE_EXCLUDE_FILES = .*\/man\/man3.* .*\/man\/man1.*

include gar/category.mk
