NAME = Struct-Compare
VERSION = 1.0.1
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ZENSPIDER

DESCRIPTION = Recursive diff for perl structures
define BLURB
  Recursive diff for perl structures
endef

DISTFILES += COPYING

PACKAGES = CSWpmstructcompare
CATALOGNAME = pm_structcompare
ARCHALL = 1

include gar/category.mk
