NAME = Carp-Clan
VERSION = 6.04
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = STBEY

DESCRIPTION = report errors from perspective of caller of a "clan" of modules
define BLURB
  This module is based on "Carp.pm" from Perl 5.005_03. It has been modified
  to skip all package names matching the pattern given in the "use" statement
  inside the "qw()" term (or argument list).
endef

PACKAGES = CSWpmcarpclan
CATALOGNAME = pm_carpclan

include gar/category.mk
