GARNAME = SAMP
GARVERSION = 1.0
CATEGORIES = meta

DESCRIPTION = Solaris Mysql Perl/PHP/Python (SAMP)
define BLURB
  The SAMP bundle package is a collection of utilities and servers that can be used to create dynamic web content.
endef

DISTFILES += $(call admfiles,CSWsamp,depend prototype)

include ../category.mk
