NAME = logtool
VERSION = 1.2.8
GARTYPE = v2

DESCRIPTION = Parse ASCII logfiles into a more palatable format
define BLURB
endef

MASTER_SITES = http://xjack.org/logtool/download/
DISTFILES = $(DISTNAME).tar.gz

GARCOMPILER = GNU

CONFIGURE_ARGS = $(DIRPATHS)

# There are no tests
SKIPTEST = 1

include gar/category.mk

