NAME = formtastic
VERSION = 0.9.10
CATEGORIES = rbgems
GARTYPE = v2

DESCRIPTION = A Rails form builder plugin
define BLURB
  A Rails form builder plugin/gem with semantically rich and accessible markup.
endef

PACKAGES = CSWgem-formtastic
CATALOGNAME = gem_formtastic

DEP_PKGS = CSWgem-actionpack CSWgem-activesupport

ARCHALL = 1

include gar/category.mk
