# $Id$

NAME		=	cssutils
VERSION		=	0.9.10b1
CATEGORIES	=	python
GARTYPE		=	v2

DESCRIPTION	=	CSS Cascading Style Sheets parser and builder
define BLURB
  A Python package to parse and build CSS Cascading Style Sheets.
  DOM only, not any rendering facilities!
endef

MASTER_SITES	=	https://bitbucket.org/cthedot/cssutils/downloads/
DISTFILES 		=	$(DISTNAME).zip

BUILD_DEP_PKGS	=	CSWpysetuptools

CONFIGURE_ARGS	=	$(DIRPATHS)

include gar/category.mk

