GARNAME = HTML-Tagset
GARVERSION = 3.04
CATEGORIES = cpan
AUTHOR = SBURKE

DESCRIPTION = data tables useful in parsing HTML
define BLURB
  This module contains several data tables useful in various kinds of HTML
  parsing operations.
endef

DISTFILES = $(call admfiles,CSWpmhtmltagset,depend prototype)

CONFIGURE_ARGS = -n

include ../category.mk
