NAME = File-pushd
VERSION = 1.002
GARTYPE = v2
CATEGORIES = cpan
AUTHOR = DAGOLDEN

DESCRIPTION = Change directory temporarily for a limited scope
define BLURB
  Change directory temporarily for a limited scope
endef

LICENSE = LICENSE

PACKAGES = CSWpm-file-pushd
CATALOGNAME = pm_file_pushd
ARCHALL = 1

CONFIGURE_ARGS = 

include gar/category.mk
