GARNAME = Time-HiRes
GARVERSION = 1.9707
CATEGORIES = cpan
AUTHOR = JHI

DESCRIPTION = high resolution alarm, sleep, gettimeofday, interval timers
define BLURB
  The Time::HiRes module implements a Perl interface to the usleep, nanosleep,
  ualarm, gettimeofday, and setitimer/getitimer system calls, in other words,
  high resolution time and timers.
endef

DISTFILES += CSWpmtimehires.gspec

include gar/category.mk
