# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = md5deep
VERSION = 4.0.0
GARTYPE = v2
CATEGORIES = utils

DESCRIPTION = Compute MD5, SHA-1, SHA-256, Tiger, or Whirlpool message digests
define BLURB
  A set of programs to compute MD5, SHA-1, SHA-256, Tiger, or Whirlpool message digests on an arbitrary number of files
endef

MASTER_SITES = $(SF_MIRRORS)
DISTFILES = $(DISTNAME).tar.gz

GARCOMPILER = GNU

CONFIGURE_ARGS = $(DIRPATHS)

include gar/category.mk

