NAME = Geography-Countries
VERSION = 2009041301
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ABIGAIL

DESCRIPTION = 2-letter, 3-letter, and numerical codes for countries
define BLURB
  This module maps country names, and their 2-letter, 3-letter and numerical
  codes, as defined by the ISO-3166 maintenance agency [1], and defined by the
  UNSD.
endef

DISTFILES = COPYING

PACKAGES = CSWpmgeocountries
CATALOGNAME = pm_geocountries

ARCHALL = 1

include gar/category.mk
