NAME = HTTP-Date
VERSION = 6.02
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = GAAS

DESCRIPTION = Date conversion routines
define BLURB
  This module provides functions that deal the date formats used by the HTTP
  protocol (and then some more). Only the first two functions, time2str() and
  str2time(), are exported by default.
endef

LICENSE_TEXT = This module is licensed under the perl license

PACKAGES = CSWpm-http-date
ARCHALL = 1

include gar/category.mk
