.TH checkpkg 8 "Jan 9, 2002" "CSW maintainers"
.SH NAME
\fBcheckpkg\fP
\- CSW utility program to check a package for standards compliance
.SH SYNOPSIS
.br
\fBcheckpkg pkg-file-name\fP

.SH DESCRIPTION
\fBcheckpkg\fP
should always be used by CSW package maintainers to check a package
before submitting it. You may call it either on a plain .pkg file, or a
 .pkg.gz file

.SH SEE ALSO
\fBstagepkg\fP(8),\fBcreatepkg\fP(8)
.SH AUTHORS
Philip Brown
.SH BUGS
Cannot cover every possible standards issue
