NAME = Crypt-DES
VERSION = 2.07
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DPARIS

DESCRIPTION = Perl DES encryption module

CATALOGNAME = pm_crypt_des
PACKAGES = CSWpm-crypt-des

include gar/category.mk
