NAME = Krb5
VERSION = 1.9
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = JHORWITZ

DESCRIPTION = Perl extension for Kerberos 5
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE_TEXT = This module is licensed under the Perl license

PACKAGING_PLATFORMS = solaris10-sparc solaris10-i386

PACKAGES += CSWpm-krb5
CATALOGNAME_CSWpm-krb5 = pm_krb5
SPKG_DESC_CSWpm-krb5 = Perl extension for Kerberos 5
RUNTIME_DEP_PKGS_CSWpm-krb5 += CSWlibkrb5-3
RUNTIME_DEP_PKGS_CSWpm-krb5 += CSWlibcom-err3
RUNTIME_DEP_PKGS_CSWpm-krb5 += CSWlibssl1-0-0

include gar/category.mk
