GARNAME = IPC-Run
GARVERSION = 0.78
CATEGORIES = cpan
AUTHOR = RBS

DESCRIPTION = system and background procs w/ piping, redirs, ptys (Unix, Win32)
define BLURB
  IPC::Run allows you run and interact with child processes using files,
  pipes, and pseudo-ttys. Both system()-style and scripted usages are
  supported and may be mixed. Likewise, functional and OO API styles are both
  supported and may be mixed.
endef

DISTFILES += $(call admfiles,CSWpmipcrun,prototype)

include gar/category.mk
