NAME = Date-Calc
VERSION = 6.3
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = STBEY

DESCRIPTION = Gregorian calendar date calculations.
define BLURB
  This package consists of a C library and a Perl module (which uses the C
  library, internally) for all kinds of date calculations based on the
  Gregorian calendar (the one used in all western countries today), thereby
  complying with all relevant norms and standards: ISO/R 2015-1971, DIN 1355
  and, to some extent, ISO 8601 (where applicable).
endef

PACKAGES = CSWpmdatecalc
CATALOGNAME = pm_datecalc

BUILD_DEP_PKGS = CSWpmbitvec CSWpmcarpclan
REQUIRES = CSWpmbitvec CSWpmcarpclan

include gar/category.mk
