NAME = Email-MIME-Attachment-Stripper
VERSION = 1.316
GARTYPE = v2
CATEGORIES = cpan
AUTHOR = RJBS

DESCRIPTION = strip the attachments from an email
define BLURB
  strip the attachments from an email
endef

PACKAGES = CSWpm-email-mime-attachment-stripper
CATALOGNAME = pm_email_mime-attachment_stripper

ARCHALL = 1
LICENSE = LICENSE

RUNTIME_DEP_PKGS += CSWpm-email-mime-contenttype
RUNTIME_DEP_PKGS += CSWpm-email-mime

include gar/category.mk

