.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH UNZOO 1 "August 23, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
unzoo \- zoo archive extractor
.SH SYNOPSIS
.B unzoo
.br
.B unzoo
.RI [-l] " [-v] " <archive>[.zoo] " [<file>..]
.br
.B unzoo
.RI -x " [-abnpo]" " [-j <prefix>]" " <archive>[.zoo]" " [<file>..]"
.SH DESCRIPTION
This manual page documents briefly the
.B unzoo
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBunzoo\fP is a program that lists or extracts the members of a zoo archive.
A zoo archive is a file that
contains several files, called its members, usually in compressed form to
save space. \fBunzoo\fP can list all or selected members or extract all or
selected members, i.e., uncompress them and write them to files. It
cannot add new members or delete members. For this you need the zoo
archiver, called \fBzoo\fP, written by Rahul Dhesi.

If you call \fBunzoo\fP with no arguments, it will first print a summary of
the commands and then prompt for command lines interactively, until you
enter an empty line.

Usually \fBunzoo\fP will only list or extract the latest generation of each
member. But if you append ';<nr>' to a path name pattern the generation
with the number <nr> is listed or extracted. <nr> itself can contain the
wildcard characters '?' and '*', so appending ';*' to a path name pattern
causes all generations to be listed or extracted.

.SH OPTIONS
A summary of options is included below.
.TP
.B \-l
list the members in the archive <archive>. For each member \fBunzoo\fP
prints the size that the extracted file would have, the compression
factor, the size that the member occupies in the archive (not counting the
space needed to store the attributes such as the path name of the file), the
date and time when the files were last modified, and finally the path name
itself. Finally \fBunzoo\fP prints a grand total for the file sizes, the
compression factor, and the member sizes.
.TP
.B <file>
list only files matching at least one pattern, '?' matches
any char, '*' matches any string.
.TP
.B \-v
list also the generation numbers and the comments, where higher numbers mean
later generations. Members for which generations are disabled are listed
with  ';0'.
.TP
.B \-x
extract the members from the archive <archive>. Members are stored with a
full path name in the archive and if the operating system supports this, they
will be extracted into appropriate subdirectories, which will be
created on demand.
.TP
.B \-a
extract all members as text files (not only those with !TEXT! comments)
.TP
.B \-b
extract all members as binary files (even those with !TEXT! comments)
.TP
.B \-n
extract no members, only test the integrity. For each member the name is
printed followed by '-- tested' if the member is intact or
by '-- error, CRC failed' if it is not.
.TP
.B \-p
extract to stdout
.TP
.B \-o
extract over existing files without asking for confirmation. The default is to
ask for confirmation. \fBunzoo\fP will never overwrite existing read-only
files.
.TP
.B \-j
prepend the string <prefix> to all path names for the members before they are
extracted. So for example if an archive contains absolute path names under
UNIX, '-j ./' can be used to convert them to relative pathnames.
Note that the directory <prefix> must exist, \fBunzoo\fP will not create it on
demand.
.SH AUTHOR
This manual page was written by Thomas Schoepf <schoepf@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
