NAME = Test-NoWarnings
VERSION = 1.02
CATEGORIES = cpan
AUTHOR = ADAMK

DESCRIPTION = Make sure you didn't emit any warnings while testing
define BLURB
  Make sure you didn't emit any warnings while testing
endef

PACKAGES = CSWpm-test-nowarnings
CATALOGNAME = pm_test_nowarnings
SPKG_DESC_CSWpm-test-nowarnings = $(DESCRIPTION)
OBSOLETES_CSWpm-test-nowarnings = CSWpmtestnowarnings
CATALOGNAME_CSWpmtestnowarnings = pm_testnowarnings

ARCHALL = 1

LICENSE = LICENSE

RUNTIME_DEP_PKGS += CSWpmtesttester

include gar/category.mk
