NAME = POE-Test-Loops
VERSION = 1.033
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = RCAPUTO

DESCRIPTION = Reusable tests for POE::Loop authors
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpoetestloops
CATALOGNAME = pm_poetestloops

ARCHALL = 1

include gar/category.mk
