#!/bin/bash

cat <<EOF
#!/bin/sh

PIR=\${PKG_INSTALL_ROOT:-/}
AP2_DIR=/opt/csw/apache2
AP2_CONF=\$PIR/etc/opt/csw/apache2
OLD_CONF=\$PIR\$AP2_DIR/etc

NEW_CONF_FILE=\$AP2_CONF/$1
OLD_CONF_FILE=\$OLD_CONF/$1

if [ "\$1" = install ]; then
   if [ -f "\$NEW_CONF_FILE" ]; then
      # existing 2.2.x install with migrated config.
      echo "Doing nothing.  Config file \$NEW_CONF_FILE in place already." >&2
   elif [ -f "\$OLD_CONF_FILE" ]; then
      # migrate old config, ensure it's updated
      echo "Importing old config file from \$OLD_CONF_FILE." >&2
      cp -p \$OLD_CONF_FILE \$NEW_CONF_FILE
      if [ -n "\`grep mod_auth.so \$NEW_CONF_FILE\`" ]; then
         echo "Updating the syntax to 2.2 format though..." >&2
         \${PIR}/\$AP2_DIR/sbin/update20to22 \$NEW_CONF_FILE >&2
      fi

      # handle the new path to default ssl key files.
      # update various uses of the var/ paths.
      # ensure we use the config files from the new location 
      perl -pi -e "s/\/opt\/csw\/apache2\/etc\/server.crt/\/etc\/opt\/csw\/apache2\/server.crt/;" -e "s/\/opt\/csw\/apache2\/etc\/server.key/\/etc\/opt\/csw\/apache2\/server.key/;" -e "s/\/opt\/csw\/apache2\/var\/log\//\/var\/opt\/csw\/log\/apache2\//;" -e "s/\"\/opt\/csw\/apache2\/var\//\"\/var\/opt\/csw\/apache2\//;" -e "s/\"var\/log\//\"\/var\/opt\/csw\/log\/apache2\//;" -e "s/ etc\// \/etc\/opt\/csw\/apache2\//;" \$NEW_CONF_FILE
   else
      # so, we're not an existing or 'needs migration' install, we must
      # install from the templates.
      echo "Installing $1 from CSW template." >&2
      cp -p \$NEW_CONF_FILE.CSW \$NEW_CONF_FILE
      perl -pi \
	-e "s/#*ServerName.*www.example.com/ServerName \`hostname\`/;" \
	-e "s/#*ServerAdmin you\@example.com/ServerAdmin root\@\`hostname\`/;" \
	-e "s/^User.*daemon/User nobody/;" \
	-e "s/^Group.*daemon/Group nobody/;" \
	-e 's/^(LoadModule.*suexec.*)/#\$1/;' \
	-e 's/^#(Include.*httpd-mpm.conf)/\$1/;' \$NEW_CONF_FILE

      chown root:bin \$NEW_CONF_FILE
      chmod 644 \$NEW_CONF_FILE
   fi
else
   echo "Not removing $1." >&2
   # preserve ourselves with no changes
   cat \$NEW_CONF_FILE
fi
EOF
