NAME = MIME-Charset
VERSION = 1.009.1
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = NEZUMI

DESCRIPTION = Charset Informations for MIME
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = ARTISTIC

PACKAGES += CSWpm-mime-charset
CATALOGNAME_CSWpm-mime-charset = pm_mime_charset
SPKG_DESC_CSWpm-mime-charset = Charset Informations for MIME
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-mime-charset = 1

include gar/category.mk
