# $Id$
# TODO (release-critical prefixed with !, non release-critical with *)
#
NAME = zsync
VERSION = 0.6.2
GARTYPE = v2

DESCRIPTION = A file transfer program

MASTER_SITES = http://zsync.moria.org.uk/download/
DISTFILES  = $(DISTNAME).tar.bz2

VENDOR_URL = http://zsync.moria.org.uk

EXTRA_CFLAGS += -xc99=all

BUILD64 = 1
ISAEXEC = 1

include gar/category.mk

