# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

GARNAME = numpy
GARVERSION = 1.4.1
CATEGORIES = python
DESCRIPTION = The fundamental package needed for scientific computing with Python
define BLURB
endef
SPKG_SOURCEURL = http://numpy.scipy.org/
PACKAGES = CSWpy-numpy
CATALOGNAME_CSWpy-numpy = py_numpy
MASTER_SITES = $(SF_MIRRORS)
DISTFILES  = $(GARNAME)-$(GARVERSION).tar.gz
UFILES_REGEX = $(GARNAME)-(\d+(?:\.\d+)*).tar.gz
TEST_SCRIPTS =
LICENSE = LICENSE.txt
include gar/category.mk
