# $Id$
NAME = xorriso
VERSION = 1.0.8
CATEGORIES = utils

DESCRIPTION = ISO 9660 Rock Ridge Filesystem Manipulator
define BLURB
endef

MASTER_SITES = $(GNU_MIRROR)
DISTFILES  = $(DISTNAME).tar.gz

RUNTIME_DEP_PKGS_CSWxorriso += CSWiconv
RUNTIME_DEP_PKGS_CSWxorriso += CSWreadline
RUNTIME_DEP_PKGS_CSWxorriso += CSWbzip2
RUNTIME_DEP_PKGS_CSWxorriso += CSWzlib

include gar/category.mk
