GARNAME = Sys-Hostname-Long
GARVERSION = 1.4
CATEGORIES = cpan
AUTHOR = SCOTT

DESCRIPTION = try every conceivable way to get full hostname
define BLURB
  This is the SECOND release of this code. It has an improved set of tests and
  improved interfaces - but it is still often failing to get a full host name.
  This of course is the reason I wrote the module, it is difficult to get full
  host names accurately on each system. On some systems (eg: Linux) it is
  dependent on the order of the entries in /etc/hosts.
endef

DISTFILES += CSWpmsyshostnamelong.gspec

include gar/category.mk
