NAME = Astro-FITS-Header
VERSION = 3.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = TJENNESS

DESCRIPTION = Object Orientated interface to FITS HDUs
define BLURB
  Astro::FITS::Header and associated sub-classes are tools for reading,
  modifying and then writing out FITS standard header blocks to FITS, NDF 
  and GSD files. The module now fully supports ESO HIERARCH header keywords.
  Support for instantiating Astro::FITS:Header objects from Starlink::AST
  FrameSet objects is also supported.
endef

PACKAGES = CSWpmastrofitsheader
CATALOGNAME = pm_astrofitsheader

# Missing dependencies (TBD):
# t/ast.t ...... skipped: Starlink::AST not available.
# t/cfitsio.t .. skipped: Astro::FITS::CFITSIO module not available
# t/gsd.t ...... skipped: GSD module not available
# t/ndf.t ...... skipped: NDF module not available


LICENSE = GPL

include gar/category.mk
