GARNAME = Convert-EBCDIC
GARVERSION = 0.06
CATEGORIES = cpan
AUTHOR = CXL

DESCRIPTION = Perl module for string conversion between EBCDIC and ASCII
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmconvertebcdic
CATALOGNAME = pm_convertebcdic

ARCHALL = 1

include gar/category.mk
