GARNAME = Graphics-ColorNames-WWW
GARVERSION = 1.13
CATEGORIES = cpan
AUTHOR = CFAERBER

DESCRIPTION = WWW color names and equivalent RGB values
define BLURB
endef

PACKAGES = CSWpmgraphicscolornw
CATALOGNAME = pm_graphicscolornw

DEP_PKGS = CSWpmgraphicscolornm

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
