#!/bin/sh
#
# cswfreeradius	Start the radiusd daemon.
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#
#    Copyright (C) 2001-2008 The FreeRADIUS Project http://www.freeradius.org
#
#    Additional modifications by OpenCSW
#FMRI network

prefix=@prefix@
exec_prefix=@exec_prefix@
sbindir=@sbindir@
localstatedir=@localstatedir@
logdir=@radius_logdir@
rundir=@radius_rundir@
sysconfdir=@sysconfdir@

#
#  If you have issues with OpenSSL, uncomment these next lines.
#
#  Something similar may work for MySQL, and you may also
#  have to LD_PRELOAD libz.so
#
#LD_LIBRARY_PATH= -lcrypto -lssl -lcrypto
#LD_RUN_PATH= -lcrypto -lssl -lcrypto:
#LD_PRELOAD= -lcrypto -lssl -lcryptolibcrypto.so
#export LD_LIBRARY_PATH LD_RUN_PATH LD_PRELOAD

RADIUSD=$sbindir/radiusd
RADDBDIR=@raddbdir@
DESC="FreeRADIUS"

#
#  See 'man radiusd' for details on command-line options.
#
ARGS=""

test -f $RADIUSD || exit 0
test -f $RADDBDIR/radiusd.conf || exit 0

if [ ! -d $rundir ] ; then
    mkdir $rundir
    chown @radius_user@:@radius_group@ $rundir
    chmod @radius_rundir_perms@ $rundir
fi

if [ ! -d $logdir ] ; then
    mkdir $logdir
    chown @radius_user@:@radius_group@ $logdir
    chmod @radius_logdir_perms@ $logdir
fi

if [ ! -f $logdir/radius.log ]; then
        touch $logdir/radius.log
fi

chown @radius_user@:@radius_group@ $logdir/radius.log
chmod 660 $logdir/radius.log

case "$1" in
  start)
	echo -n "Starting $DESC:"
	$RADIUSD $ARGS
	echo "radiusd"
	;;
  stop)
	[ -z "$2" ] && echo -n "Stopping $DESC: "
        [ -f $rundir/radiusd.pid ] && kill -TERM `cat $rundir/radiusd.pid`
	[ -z "$2" ] && echo "radiusd."
	;;
  reload|force-reload)
	echo "Reloading $DESC configuration files."
	[ -f $rundir/radiusd.pid ] && kill -HUP `cat $rundir/radiusd.pid`
	;;
  restart)
	sh $0 stop quiet
	sleep 3
	sh $0 start
	;;
  check)
  	$RADIUSD -C $ARGS
	;;
  *)
        echo "Usage: $0 {start|stop|reload|restart|check}"
        exit 1
esac

exit 0
