PHP5EXT_NAME = dom

PACKAGES += CSWphp5dom

CATALOGNAME_CSWphp5dom = php5_dom
SPKG_DESC_CSWphp5dom = dom Extention for PHP5
REQUIRED_PKGS_CSWphp5dom = CSWphp5 CSWiconv CSWlibxml2 CSWzlib

CONFIGURE_ARGS += --enable-dom=shared
CONFIGURE_ARGS += --with-libxml-dir=$(prefix)

PKGFILES_CSWphp5dom = .*/lib/php/extensions/.*/dom.*
