NAME = Task-Weaken
VERSION = 1.03
CATEGORIES = cpan
AUTHOR = ADAMK

DESCRIPTION = Ensure that a platform has weaken support
define BLURB
endef

PACKAGES = CSWpmtaskweaken
CATALOGNAME = pm_taskweaken

LICENSE = LICENSE

ARCHALL = 1

include gar/category.mk
