NAME = Task-Weaken
VERSION = 1.04
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = ADAMK

DESCRIPTION = Ensure that a platform has weaken support
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-task-weaken
CATALOGNAME_CSWpm-task-weaken = pm_task_weaken
SPKG_DESC_CSWpm-task-weaken = Ensure that a platform has weaken support
ARCHALL_CSWpm-task-weaken = 1
OBSOLETED_BY_CSWpm-task-weaken += CSWpmtaskweaken
CATALOGNAME_CSWpmtaskweaken = pm_taskweaken_stub

include gar/category.mk
