NAME = Test-Output
VERSION = 1.01
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = BDFOY

DESCRIPTION = Utilities to test STDOUT and STDERR messages
define BLURB
endef

CATALOG_RELEASE = unstable

LICENSE = LICENSE

PACKAGES += CSWpm-test-output
CATALOGNAME_CSWpm-test-output = pm_test_output
SPKG_DESC_CSWpm-test-output = Utilities to test STDOUT and STDERR messages
# There was no information if this is pure Perl or not. Please remove if necessary.
ARCHALL_CSWpm-test-output = 1
RUNTIME_DEP_PKGS_CSWpm-test-output += CSWpm-sub-exporter
RUNTIME_DEP_PKGS_CSWpm-test-output += CSWpm-test-tester

include gar/category.mk
