NAME = Mail-Box
VERSION = 2.093
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = MARKOV

DESCRIPTION = Manage a mailbox, a folder with messages
define BLURB
  Mail::Box is the base class for accessing various types of mailboxes
  (folders) in a uniform manner. The various folder types vary on how they
  store their messages, but when some effort those differences could be hidden
  behind a general API. For example, some folders store many messages in one
  single file, where other store each message in a separate file withing the
  same directory.
endef

PACKAGES = CSWpmmailbox
CATALOGNAME = pm_mailbox

LICENSE = LICENSE

# TBD: Add a ton of dependencies, including libdbx from http://sourceforge.net/project/ol2mbox/

ARCHALL = 1

include gar/category.mk
