PHP5EXT_NAME = pcntl

PACKAGES += CSWphp5pcntl

CATALOGNAME_CSWphp5pcntl = php5_pcntl
SPKG_DESC_CSWphp5pcntl = pcntl Extention for PHP5
REQUIRED_PKGS_CSWphp5pcntl = CSWphp5

CONFIGURE_ARGS += --enable-pcntl=shared

PKGFILES_CSWphp5pcntl = .*/lib/php/extensions/.*/pcntl.*
