diff --speed-large-files --minimal -Nru nsca-2.7.2.orig/Makefile.in nsca-2.7.2/Makefile.in
--- nsca-2.7.2.orig/Makefile.in	2003-10-16 01:17:45.000000000 +0200
+++ nsca-2.7.2/Makefile.in	2009-02-11 10:25:05.717351194 +0100
@@ -9,6 +9,15 @@
 SRC_BASE=./src/
 SRC_INCLUDE=./include/
 
+prefix=@prefix@
+BINDIR=@bindir@
+NAGIOSBINDIR=@prefix@/nagios/bin
+NAGIOSCFGDIR=@prefix@/nagios/etc
+CFGDIR=@sysconfdir@
+NSCADOCDIR=$(prefix)/share/doc/nsca
+SENDNSCADOCDIR=@prefix@/share/doc/send_nsca
+INSTALL=@INSTALL@
+
 all:	
 	cd $(SRC_BASE); $(MAKE) $@ ; cd ..
 
@@ -35,6 +44,26 @@
 	@echo "client and server binaries."
 	@echo ""
 
+install-nsca:
+	$(INSTALL) -m 755 src/nsca $(DESTDIR)$(NAGIOSBINDIR)
+	$(INSTALL) -m 600 sample-config/nsca.cfg $(DESTDIR)$(NAGIOSCFGDIR)/nsca.cfg
+	$(INSTALL) -m 755 -d $(DESTDIR)$(NSCADOCDIR)
+	$(INSTALL) -m 644 ./Changelog $(DESTDIR)$(NSCADOCDIR)
+	$(INSTALL) -m 644 ./LEGAL $(DESTDIR)$(NSCADOCDIR)
+	$(INSTALL) -m 644 ./README $(DESTDIR)$(NSCADOCDIR)
+	$(INSTALL) -m 644 ./SECURITY $(DESTDIR)$(NSCADOCDIR)
+
+install-sendnsca:
+	$(INSTALL) -m 755 src/send_nsca $(DESTDIR)$(BINDIR)
+	$(INSTALL) -m 755 -d $(DESTDIR)$(SENDNSCADOCDIR)
+	$(INSTALL) -m 755 -d $(DESTDIR)$(CFGDIR)
+	$(INSTALL) -m 755 src/submit_check_result-sample $(DESTDIR)$(SENDNSCADOCDIR)
+	$(INSTALL) -m 600 sample-config/send_nsca.cfg $(DESTDIR)$(CFGDIR)/send_nsca.cfg
+	$(INSTALL) -m 644 ./Changelog $(DESTDIR)$(SENDNSCADOCDIR)
+	$(INSTALL) -m 644 ./LEGAL $(DESTDIR)$(SENDNSCADOCDIR)
+	$(INSTALL) -m 644 ./README $(DESTDIR)$(SENDNSCADOCDIR)
+	$(INSTALL) -m 644 ./SECURITY $(DESTDIR)$(SENDNSCADOCDIR)
+
 clean:
 	cd $(SRC_BASE); $(MAKE) $@ ; cd ..
 	rm -f core
