NAME = Try-Tiny
VERSION = 0.11
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = DOY

DESCRIPTION = Minimal try/catch with proper localization
define BLURB
endef

DISTFILES += COPYING

CATALOG_RELEASE = unstable

PACKAGES += CSWpm-try-tiny
SPKG_DESC_CSWpm-try-tiny = Minimal try/catch with proper localization
ARCHALL_CSWpm-try-tiny = 1

include gar/category.mk
