# Copyright 2009 OpenCSW
# Distributed under the terms of the GNU General Public License v2
# $Id$

NAME = Werkzeug
VERSION = 0.9.4
CATEGORIES = python
GARTYPE = v2
DESCRIPTION = The Swiss Army knife of Python web development

VENDOR_URL = https://pypi.python.org/pypi/Werkzeug

DISTFILES  = $(NAME)-$(VERSION).tar.gz

PACKAGES = CSWpy-werkzeug
ARCHALL_CSWpy-werkzeug = 1

include gar/category.mk
