NAME = DublinCore-Record
VERSION = 0.03
CATEGORIES = cpan
GARTYPE = v2
AUTHOR = BRICAS

DESCRIPTION = Container for Dublin Core metadata elements
define BLURB
endef

DISTFILES = COPYING

PACKAGES = CSWpmdublincorerecrd
CATALOGNAME = pm_dublincorerecord

ARCHALL = 1

include gar/category.mk
