GARNAME = Class-ReturnValue
GARVERSION = 0.55
CATEGORIES = cpan
AUTHOR = JESSE

DESCRIPTION = Treat a return value as boolean, array or object
define BLURB
  Class::ReturnValue is a return value object that can allow code calling your
  routine to expect: a boolean value (did it fail) or a list (what are the
  return values)
endef

PREREQUISITE_PKGS = CSWpmtestinline
REQUIRED_PKGS = CSWpmdevstacktrace

PACKAGES = CSWpmclassretval
CATALOGNAME = pm_classretval

ARCHALL = 1

include gar/category.mk
